
DROP TABLE IF EXISTS `contrexx_module_shop_config`;
CREATE TABLE IF NOT EXISTS `contrexx_module_shop_config` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(64) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `value` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `status` tinyint(1) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=79 ;

--
-- Dumping data for table `contrexx_module_shop_config`
--

INSERT INTO `contrexx_module_shop_config` (`id`, `name`, `value`, `status`) VALUES
(21, 'email', 'info@example.com', 0),
(22, 'tax_number', '99999', 0),
(23, 'tax_included', '1', 0),
(28, 'saferpay_id', '12345-12345678', 1),
(29, 'yellowpay_id', 'demo', 0),
(30, 'yellowpay_hash_seed', 'demo', 0),
(31, 'confirmation_emails', 'info@example.com', 0),
(32, 'telephone', '012 3456789', 0),
(33, 'fax', '012 3456790', 0),
(34, 'yellowpay_authorization_type', 'SAL', 0),
(35, 'paypal_account_email', 'info@example.com', 1),
(36, 'yellowpay_shop_id', '1111', 1),
(37, 'country_id', '204', 0),
(38, 'saferpay_use_test_account', '0', 1),
(39, 'saferpay_finalize_payment', '1', 0),
(40, 'saferpay_window_option', '2', 0),
(41, 'paypal_default_currency', 'EUR', 0),
(42, 'tax_enabled', '1', 0),
(43, 'tax_default_id', '1', 0),
(44, 'payment_lsv_status', '', 1),
(45, 'shop_company', 'Beispiel AG', 0),
(46, 'shop_address', 'Firmenstrasse 1\r\n4321 Irgendwo\r\n', 0),
(47, 'shop_thumbnail_max_width', '140', 0),
(48, 'shop_thumbnail_max_height', '140', 0),
(49, 'shop_thumbnail_quality', '95', 0),
(52, 'shop_weight_enable', '0', 0),
(53, 'yellowpay_accepted_payment_methods', 'PostFinanceCard,yellownet,Master,Visa,Amex,Diners', 0),
(54, 'yellowpay_use_testserver', '1', 0),
(55, 'product_sorting', '1', 0),
(56, 'datatrans_merchant_id', '123456789', 0),
(57, 'datatrans_status', '1', 0),
(58, 'datatrans_request_type', 'NOA', 0),
(59, 'datatrans_use_testserver', '1', 0),
(60, 'shop_show_products_default', '0', 0),
(61, 'yellowpay_hash_signature_in', '', 0),
(62, 'yellowpay_hash_signature_out', '', 0),
(63, 'postfinance_mobile_webuser', '', 0),
(64, 'postfinance_mobile_sign', '', 0),
(65, 'postfinance_mobile_ijustwanttotest', '', 0),
(66, 'postfinance_mobile_status', '', 0),
(67, 'orderitems_amount_max', '0.00', 0),
(68, 'vat_number', '', 0),
(69, 'vat_default_id', '1', 0),
(70, 'vat_other_id', '1', 0),
(71, 'vat_enabled_home_customer', '0', 0),
(72, 'vat_enabled_home_reseller', '0', 0),
(73, 'vat_enabled_foreign_customer', '0', 0),
(74, 'vat_enabled_foreign_reseller', '0', 0),
(75, 'vat_included_home_customer', '0', 0),
(76, 'vat_included_home_reseller', '0', 0),
(77, 'vat_included_foreign_customer', '0', 0),
(78, 'vat_included_foreign_reseller', '0', 0);
