<?php

namespace Cx\Core_Modules\MultiSite\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WebsiteServiceServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteServiceServerRepository extends EntityRepository{
    
}
