<?php

namespace Cx\Model\Proxies\__CG__\Cx\Core_Modules\Sync\Model\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Change extends \Cx\Core_Modules\Sync\Model\Entity\Change implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

        return parent::__get($name);
    }





    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'sync', 'originSync', 'hosts', 'eventType', 'condition', 'entityIndexData', 'originEntityIndexData', 'entity', 'contents', 'validators', 'virtual');
        }

        return array('__isInitialized__', 'id', 'sync', 'originSync', 'hosts', 'eventType', 'condition', 'entityIndexData', 'originEntityIndexData', 'entity', 'contents', 'validators', 'virtual');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Change $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSync($sync)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSync', array($sync));

        return parent::setSync($sync);
    }

    /**
     * {@inheritDoc}
     */
    public function getSync()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSync', array());

        return parent::getSync();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginSync($originSync)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginSync', array($originSync));

        return parent::setOriginSync($originSync);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginSync()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginSync', array());

        return parent::getOriginSync();
    }

    /**
     * {@inheritDoc}
     */
    public function addHost($host)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addHost', array($host));

        return parent::addHost($host);
    }

    /**
     * {@inheritDoc}
     */
    public function removeHost($host)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeHost', array($host));

        return parent::removeHost($host);
    }

    /**
     * {@inheritDoc}
     */
    public function setHosts($hosts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHosts', array($hosts));

        return parent::setHosts($hosts);
    }

    /**
     * {@inheritDoc}
     */
    public function getHosts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHosts', array());

        return parent::getHosts();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventType($eventType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventType', array($eventType));

        return parent::setEventType($eventType);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventType', array());

        return parent::getEventType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCondition($condition)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCondition', array($condition));

        return parent::setCondition($condition);
    }

    /**
     * {@inheritDoc}
     */
    public function getCondition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCondition', array());

        return parent::getCondition();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntityIndexData($entityIndexData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntityIndexData', array($entityIndexData));

        return parent::setEntityIndexData($entityIndexData);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityIndexData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityIndexData', array());

        return parent::getEntityIndexData();
    }

    /**
     * {@inheritDoc}
     */
    public function setOriginEntityIndexData($originEntityIndexData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOriginEntityIndexData', array($originEntityIndexData));

        return parent::setOriginEntityIndexData($originEntityIndexData);
    }

    /**
     * {@inheritDoc}
     */
    public function getOriginEntityIndexData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOriginEntityIndexData', array());

        return parent::getOriginEntityIndexData();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntity($entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntity', array($entity));

        return parent::setEntity($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntity', array());

        return parent::getEntity();
    }

    /**
     * {@inheritDoc}
     */
    public function setContents($contents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContents', array($contents));

        return parent::setContents($contents);
    }

    /**
     * {@inheritDoc}
     */
    public function getContents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContents', array());

        return parent::getContents();
    }

    /**
     * {@inheritDoc}
     */
    public function setMode($hostEventType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMode', array($hostEventType));

        return parent::setMode($hostEventType);
    }

    /**
     * {@inheritDoc}
     */
    public function getComponentController()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComponentController', array());

        return parent::getComponentController();
    }

    /**
     * {@inheritDoc}
     */
    public function setVirtual($virtual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVirtual', array($virtual));

        return parent::setVirtual($virtual);
    }

    /**
     * {@inheritDoc}
     */
    public function isVirtual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isVirtual', array());

        return parent::isVirtual();
    }

    /**
     * {@inheritDoc}
     */
    public function initializeValidators()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'initializeValidators', array());

        return parent::initializeValidators();
    }

    /**
     * {@inheritDoc}
     */
    public function validate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'validate', array());

        return parent::validate();
    }

    /**
     * {@inheritDoc}
     */
    public function __call($methodName, $arguments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', array($methodName, $arguments));

        return parent::__call($methodName, $arguments);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
