<?php

namespace Cx\Model\Proxies\__CG__\Cx\Modules\Calendar\Model\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Event extends \Cx\Modules\Calendar\Model\Entity\Event implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

        return parent::__get($name);
    }





    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'type', 'startDate', 'endDate', 'useCustomDateDisplay', 'showStartDateList', 'showEndDateList', 'showStartTimeList', 'showEndTimeList', 'showTimeTypeList', 'showStartDateDetail', 'showEndDateDetail', 'showStartTimeDetail', 'showEndTimeDetail', 'showTimeTypeDetail', 'google', 'access', 'priority', 'price', 'link', 'pic', 'attach', 'placeMediadirId', 'showIn', 'invitedGroups', 'invitedCrmGroups', 'excludedCrmGroups', 'invitedMails', 'invitationSent', 'invitationEmailTemplate', 'registration', 'registrationNum', 'registrationNotification', 'emailTemplate', 'ticketSales', 'numSeating', 'seriesStatus', 'independentSeries', 'seriesType', 'seriesPatternCount', 'seriesPatternWeekday', 'seriesPatternDay', 'seriesPatternWeek', 'seriesPatternMonth', 'seriesPatternType', 'seriesPatternDouranceType', 'seriesPatternEnd', 'seriesPatternEndDate', 'seriesPatternBegin', 'seriesPatternExceptions', 'seriesAdditionalRecurrences', 'status', 'confirmed', 'showDetailView', 'author', 'allDay', 'locationType', 'placeId', 'placeStreet', 'placeWebsite', 'placeZip', 'placeLink', 'placePhone', 'placeMap', 'hostType', 'orgName', 'orgStreet', 'orgWebsite', 'orgZip', 'orgLink', 'orgPhone', 'orgEmail', 'hostMediadirId', 'registrationExternalLink', 'registrationExternalFullyBooked', 'eventFields', 'invite', 'registrations', 'categories', 'registrationForm', 'validators', 'virtual');
        }

        return array('__isInitialized__', 'id', 'type', 'startDate', 'endDate', 'useCustomDateDisplay', 'showStartDateList', 'showEndDateList', 'showStartTimeList', 'showEndTimeList', 'showTimeTypeList', 'showStartDateDetail', 'showEndDateDetail', 'showStartTimeDetail', 'showEndTimeDetail', 'showTimeTypeDetail', 'google', 'access', 'priority', 'price', 'link', 'pic', 'attach', 'placeMediadirId', 'showIn', 'invitedGroups', 'invitedCrmGroups', 'excludedCrmGroups', 'invitedMails', 'invitationSent', 'invitationEmailTemplate', 'registration', 'registrationNum', 'registrationNotification', 'emailTemplate', 'ticketSales', 'numSeating', 'seriesStatus', 'independentSeries', 'seriesType', 'seriesPatternCount', 'seriesPatternWeekday', 'seriesPatternDay', 'seriesPatternWeek', 'seriesPatternMonth', 'seriesPatternType', 'seriesPatternDouranceType', 'seriesPatternEnd', 'seriesPatternEndDate', 'seriesPatternBegin', 'seriesPatternExceptions', 'seriesAdditionalRecurrences', 'status', 'confirmed', 'showDetailView', 'author', 'allDay', 'locationType', 'placeId', 'placeStreet', 'placeWebsite', 'placeZip', 'placeLink', 'placePhone', 'placeMap', 'hostType', 'orgName', 'orgStreet', 'orgWebsite', 'orgZip', 'orgLink', 'orgPhone', 'orgEmail', 'hostMediadirId', 'registrationExternalLink', 'registrationExternalFullyBooked', 'eventFields', 'invite', 'registrations', 'categories', 'registrationForm', 'validators', 'virtual');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Event $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartDate($startDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartDate', array($startDate));

        return parent::setStartDate($startDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartDate', array());

        return parent::getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndDate($endDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndDate', array($endDate));

        return parent::setEndDate($endDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndDate', array());

        return parent::getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUseCustomDateDisplay($useCustomDateDisplay)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUseCustomDateDisplay', array($useCustomDateDisplay));

        return parent::setUseCustomDateDisplay($useCustomDateDisplay);
    }

    /**
     * {@inheritDoc}
     */
    public function getUseCustomDateDisplay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUseCustomDateDisplay', array());

        return parent::getUseCustomDateDisplay();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowStartDateList($showStartDateList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowStartDateList', array($showStartDateList));

        return parent::setShowStartDateList($showStartDateList);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowStartDateList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowStartDateList', array());

        return parent::getShowStartDateList();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowEndDateList($showEndDateList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowEndDateList', array($showEndDateList));

        return parent::setShowEndDateList($showEndDateList);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowEndDateList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowEndDateList', array());

        return parent::getShowEndDateList();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowStartTimeList($showStartTimeList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowStartTimeList', array($showStartTimeList));

        return parent::setShowStartTimeList($showStartTimeList);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowStartTimeList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowStartTimeList', array());

        return parent::getShowStartTimeList();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowEndTimeList($showEndTimeList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowEndTimeList', array($showEndTimeList));

        return parent::setShowEndTimeList($showEndTimeList);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowEndTimeList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowEndTimeList', array());

        return parent::getShowEndTimeList();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowTimeTypeList($showTimeTypeList)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowTimeTypeList', array($showTimeTypeList));

        return parent::setShowTimeTypeList($showTimeTypeList);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowTimeTypeList()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowTimeTypeList', array());

        return parent::getShowTimeTypeList();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowStartDateDetail($showStartDateDetail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowStartDateDetail', array($showStartDateDetail));

        return parent::setShowStartDateDetail($showStartDateDetail);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowStartDateDetail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowStartDateDetail', array());

        return parent::getShowStartDateDetail();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowEndDateDetail($showEndDateDetail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowEndDateDetail', array($showEndDateDetail));

        return parent::setShowEndDateDetail($showEndDateDetail);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowEndDateDetail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowEndDateDetail', array());

        return parent::getShowEndDateDetail();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowStartTimeDetail($showStartTimeDetail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowStartTimeDetail', array($showStartTimeDetail));

        return parent::setShowStartTimeDetail($showStartTimeDetail);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowStartTimeDetail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowStartTimeDetail', array());

        return parent::getShowStartTimeDetail();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowEndTimeDetail($showEndTimeDetail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowEndTimeDetail', array($showEndTimeDetail));

        return parent::setShowEndTimeDetail($showEndTimeDetail);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowEndTimeDetail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowEndTimeDetail', array());

        return parent::getShowEndTimeDetail();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowTimeTypeDetail($showTimeTypeDetail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowTimeTypeDetail', array($showTimeTypeDetail));

        return parent::setShowTimeTypeDetail($showTimeTypeDetail);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowTimeTypeDetail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowTimeTypeDetail', array());

        return parent::getShowTimeTypeDetail();
    }

    /**
     * {@inheritDoc}
     */
    public function setGoogle($google)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoogle', array($google));

        return parent::setGoogle($google);
    }

    /**
     * {@inheritDoc}
     */
    public function getGoogle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoogle', array());

        return parent::getGoogle();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccess($access)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccess', array($access));

        return parent::setAccess($access);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccess()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccess', array());

        return parent::getAccess();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriority($priority)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriority', array($priority));

        return parent::setPriority($priority);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriority()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriority', array());

        return parent::getPriority();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setLink($link)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLink', array($link));

        return parent::setLink($link);
    }

    /**
     * {@inheritDoc}
     */
    public function getLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLink', array());

        return parent::getLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setPic($pic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPic', array($pic));

        return parent::setPic($pic);
    }

    /**
     * {@inheritDoc}
     */
    public function getPic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPic', array());

        return parent::getPic();
    }

    /**
     * {@inheritDoc}
     */
    public function setAttach($attach)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttach', array($attach));

        return parent::setAttach($attach);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttach()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttach', array());

        return parent::getAttach();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceMediadirId($placeMediadirId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceMediadirId', array($placeMediadirId));

        return parent::setPlaceMediadirId($placeMediadirId);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceMediadirId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceMediadirId', array());

        return parent::getPlaceMediadirId();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowIn($showIn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowIn', array($showIn));

        return parent::setShowIn($showIn);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowIn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowIn', array());

        return parent::getShowIn();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvitedGroups($invitedGroups)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvitedGroups', array($invitedGroups));

        return parent::setInvitedGroups($invitedGroups);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvitedGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvitedGroups', array());

        return parent::getInvitedGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvitedCrmGroups($invitedCrmGroups)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvitedCrmGroups', array($invitedCrmGroups));

        return parent::setInvitedCrmGroups($invitedCrmGroups);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvitedCrmGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvitedCrmGroups', array());

        return parent::getInvitedCrmGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function setExcludedCrmGroups($excludedCrmGroups)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExcludedCrmGroups', array($excludedCrmGroups));

        return parent::setExcludedCrmGroups($excludedCrmGroups);
    }

    /**
     * {@inheritDoc}
     */
    public function getExcludedCrmGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExcludedCrmGroups', array());

        return parent::getExcludedCrmGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvitedMails($invitedMails)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvitedMails', array($invitedMails));

        return parent::setInvitedMails($invitedMails);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvitedMails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvitedMails', array());

        return parent::getInvitedMails();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvitationSent($invitationSent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvitationSent', array($invitationSent));

        return parent::setInvitationSent($invitationSent);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvitationSent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvitationSent', array());

        return parent::getInvitationSent();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvitationEmailTemplate($invitationEmailTemplate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvitationEmailTemplate', array($invitationEmailTemplate));

        return parent::setInvitationEmailTemplate($invitationEmailTemplate);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvitationEmailTemplate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvitationEmailTemplate', array());

        return parent::getInvitationEmailTemplate();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistration($registration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistration', array($registration));

        return parent::setRegistration($registration);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistration', array());

        return parent::getRegistration();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistrationNum($registrationNum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistrationNum', array($registrationNum));

        return parent::setRegistrationNum($registrationNum);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationNum', array());

        return parent::getRegistrationNum();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistrationNotification($registrationNotification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistrationNotification', array($registrationNotification));

        return parent::setRegistrationNotification($registrationNotification);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationNotification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationNotification', array());

        return parent::getRegistrationNotification();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailTemplate($emailTemplate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailTemplate', array($emailTemplate));

        return parent::setEmailTemplate($emailTemplate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailTemplate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailTemplate', array());

        return parent::getEmailTemplate();
    }

    /**
     * {@inheritDoc}
     */
    public function getMail($mailString)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMail', array($mailString));

        return parent::getMail($mailString);
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketSales($ticketSales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketSales', array($ticketSales));

        return parent::setTicketSales($ticketSales);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketSales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketSales', array());

        return parent::getTicketSales();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumSeating($numSeating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumSeating', array($numSeating));

        return parent::setNumSeating($numSeating);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumSeating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumSeating', array());

        return parent::getNumSeating();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriesStatus($seriesStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriesStatus', array($seriesStatus));

        return parent::setSeriesStatus($seriesStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriesStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriesStatus', array());

        return parent::getSeriesStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndependentSeries($independentSeries)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndependentSeries', array($independentSeries));

        return parent::setIndependentSeries($independentSeries);
    }

    /**
     * {@inheritDoc}
     */
    public function getIndependentSeries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIndependentSeries', array());

        return parent::getIndependentSeries();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriesType($seriesType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriesType', array($seriesType));

        return parent::setSeriesType($seriesType);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriesType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriesType', array());

        return parent::getSeriesType();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriesPatternCount($seriesPatternCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriesPatternCount', array($seriesPatternCount));

        return parent::setSeriesPatternCount($seriesPatternCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriesPatternCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriesPatternCount', array());

        return parent::getSeriesPatternCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriesPatternWeekday($seriesPatternWeekday)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriesPatternWeekday', array($seriesPatternWeekday));

        return parent::setSeriesPatternWeekday($seriesPatternWeekday);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriesPatternWeekday()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriesPatternWeekday', array());

        return parent::getSeriesPatternWeekday();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriesPatternDay($seriesPatternDay)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriesPatternDay', array($seriesPatternDay));

        return parent::setSeriesPatternDay($seriesPatternDay);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriesPatternDay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriesPatternDay', array());

        return parent::getSeriesPatternDay();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriesPatternWeek($seriesPatternWeek)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriesPatternWeek', array($seriesPatternWeek));

        return parent::setSeriesPatternWeek($seriesPatternWeek);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriesPatternWeek()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriesPatternWeek', array());

        return parent::getSeriesPatternWeek();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriesPatternMonth($seriesPatternMonth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriesPatternMonth', array($seriesPatternMonth));

        return parent::setSeriesPatternMonth($seriesPatternMonth);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriesPatternMonth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriesPatternMonth', array());

        return parent::getSeriesPatternMonth();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriesPatternType($seriesPatternType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriesPatternType', array($seriesPatternType));

        return parent::setSeriesPatternType($seriesPatternType);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriesPatternType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriesPatternType', array());

        return parent::getSeriesPatternType();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriesPatternDouranceType($seriesPatternDouranceType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriesPatternDouranceType', array($seriesPatternDouranceType));

        return parent::setSeriesPatternDouranceType($seriesPatternDouranceType);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriesPatternDouranceType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriesPatternDouranceType', array());

        return parent::getSeriesPatternDouranceType();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriesPatternEnd($seriesPatternEnd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriesPatternEnd', array($seriesPatternEnd));

        return parent::setSeriesPatternEnd($seriesPatternEnd);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriesPatternEnd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriesPatternEnd', array());

        return parent::getSeriesPatternEnd();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriesPatternEndDate($seriesPatternEndDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriesPatternEndDate', array($seriesPatternEndDate));

        return parent::setSeriesPatternEndDate($seriesPatternEndDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriesPatternEndDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriesPatternEndDate', array());

        return parent::getSeriesPatternEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriesPatternBegin($seriesPatternBegin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriesPatternBegin', array($seriesPatternBegin));

        return parent::setSeriesPatternBegin($seriesPatternBegin);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriesPatternBegin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriesPatternBegin', array());

        return parent::getSeriesPatternBegin();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriesPatternExceptions($seriesPatternExceptions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriesPatternExceptions', array($seriesPatternExceptions));

        return parent::setSeriesPatternExceptions($seriesPatternExceptions);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriesPatternExceptions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriesPatternExceptions', array());

        return parent::getSeriesPatternExceptions();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriesAdditionalRecurrences($seriesAdditionalRecurrences)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriesAdditionalRecurrences', array($seriesAdditionalRecurrences));

        return parent::setSeriesAdditionalRecurrences($seriesAdditionalRecurrences);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriesAdditionalRecurrences()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriesAdditionalRecurrences', array());

        return parent::getSeriesAdditionalRecurrences();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmed($confirmed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmed', array($confirmed));

        return parent::setConfirmed($confirmed);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmed', array());

        return parent::getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowDetailView($showDetailView)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowDetailView', array($showDetailView));

        return parent::setShowDetailView($showDetailView);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowDetailView()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowDetailView', array());

        return parent::getShowDetailView();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthor($author)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthor', array($author));

        return parent::setAuthor($author);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthor', array());

        return parent::getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setAllDay($allDay)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAllDay', array($allDay));

        return parent::setAllDay($allDay);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllDay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllDay', array());

        return parent::getAllDay();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocationType($locationType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocationType', array($locationType));

        return parent::setLocationType($locationType);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocationType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocationType', array());

        return parent::getLocationType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceId($placeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceId', array($placeId));

        return parent::setPlaceId($placeId);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceId', array());

        return parent::getPlaceId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceStreet($placeStreet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceStreet', array($placeStreet));

        return parent::setPlaceStreet($placeStreet);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceStreet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceStreet', array());

        return parent::getPlaceStreet();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceZip($placeZip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceZip', array($placeZip));

        return parent::setPlaceZip($placeZip);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceZip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceZip', array());

        return parent::getPlaceZip();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceWebsite($placeWebsite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceWebsite', array($placeWebsite));

        return parent::setPlaceWebsite($placeWebsite);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceWebsite', array());

        return parent::getPlaceWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceLink($placeLink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceLink', array($placeLink));

        return parent::setPlaceLink($placeLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceLink', array());

        return parent::getPlaceLink();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlacePhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlacePhone', array());

        return parent::getPlacePhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlacePhone($placePhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlacePhone', array($placePhone));

        return parent::setPlacePhone($placePhone);
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaceMap($placeMap)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaceMap', array($placeMap));

        return parent::setPlaceMap($placeMap);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaceMap()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaceMap', array());

        return parent::getPlaceMap();
    }

    /**
     * {@inheritDoc}
     */
    public function setHostType($hostType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHostType', array($hostType));

        return parent::setHostType($hostType);
    }

    /**
     * {@inheritDoc}
     */
    public function getHostType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHostType', array());

        return parent::getHostType();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrgStreet($orgStreet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrgStreet', array($orgStreet));

        return parent::setOrgStreet($orgStreet);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrgStreet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrgStreet', array());

        return parent::getOrgStreet();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrgZip($orgZip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrgZip', array($orgZip));

        return parent::setOrgZip($orgZip);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrgZip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrgZip', array());

        return parent::getOrgZip();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrgWebsite($orgWebsite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrgWebsite', array($orgWebsite));

        return parent::setOrgWebsite($orgWebsite);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrgWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrgWebsite', array());

        return parent::getOrgWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrgLink($orgLink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrgLink', array($orgLink));

        return parent::setOrgLink($orgLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrgLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrgLink', array());

        return parent::getOrgLink();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrgPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrgPhone', array());

        return parent::getOrgPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrgPhone($orgPhone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrgPhone', array($orgPhone));

        return parent::setOrgPhone($orgPhone);
    }

    /**
     * {@inheritDoc}
     */
    public function setOrgEmail($orgEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrgEmail', array($orgEmail));

        return parent::setOrgEmail($orgEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrgEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrgEmail', array());

        return parent::getOrgEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setHostMediadirId($hostMediadirId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHostMediadirId', array($hostMediadirId));

        return parent::setHostMediadirId($hostMediadirId);
    }

    /**
     * {@inheritDoc}
     */
    public function getHostMediadirId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHostMediadirId', array());

        return parent::getHostMediadirId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistrationExternalLink($registrationExternalLink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistrationExternalLink', array($registrationExternalLink));

        return parent::setRegistrationExternalLink($registrationExternalLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationExternalLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationExternalLink', array());

        return parent::getRegistrationExternalLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistrationExternalFullyBooked($registrationExternalFullyBooked)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistrationExternalFullyBooked', array($registrationExternalFullyBooked));

        return parent::setRegistrationExternalFullyBooked($registrationExternalFullyBooked);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationExternalFullyBooked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationExternalFullyBooked', array());

        return parent::getRegistrationExternalFullyBooked();
    }

    /**
     * {@inheritDoc}
     */
    public function addEventField(\Cx\Modules\Calendar\Model\Entity\EventField $eventField)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEventField', array($eventField));

        return parent::addEventField($eventField);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEventField(\Cx\Modules\Calendar\Model\Entity\EventField $eventFields)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEventField', array($eventFields));

        return parent::removeEventField($eventFields);
    }

    /**
     * {@inheritDoc}
     */
    public function setEventFields($eventFields)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventFields', array($eventFields));

        return parent::setEventFields($eventFields);
    }

    /**
     * {@inheritDoc}
     */
    public function setInvite($invite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvite', array($invite));

        return parent::setInvite($invite);
    }

    /**
     * {@inheritDoc}
     */
    public function addInvite(\Cx\Modules\Calendar\Model\Entity\Invite $invite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInvite', array($invite));

        return parent::addInvite($invite);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInvite(\Cx\Modules\Calendar\Model\Entity\Invite $invite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInvite', array($invite));

        return parent::removeInvite($invite);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvite', array());

        return parent::getInvite();
    }

    /**
     * {@inheritDoc}
     */
    public function getEventFieldByLangId($langId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventFieldByLangId', array($langId));

        return parent::getEventFieldByLangId($langId);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventFields()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventFields', array());

        return parent::getEventFields();
    }

    /**
     * {@inheritDoc}
     */
    public function addRegistration(\Cx\Modules\Calendar\Model\Entity\Registration $registration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRegistration', array($registration));

        return parent::addRegistration($registration);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRegistration(\Cx\Modules\Calendar\Model\Entity\Registration $registrations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRegistration', array($registrations));

        return parent::removeRegistration($registrations);
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistrations($registrations)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistrations', array($registrations));

        return parent::setRegistrations($registrations);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrations', array());

        return parent::getRegistrations();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategories(\Doctrine\Common\Collections\Collection $categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategories', array($categories));

        return parent::setCategories($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', array());

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function addCategories($category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategories', array($category));

        return parent::addCategories($category);
    }

    /**
     * {@inheritDoc}
     */
    public function addCategory(\Cx\Modules\Calendar\Model\Entity\Category $categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategory', array($categories));

        return parent::addCategory($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategory(\Cx\Modules\Calendar\Model\Entity\Category $categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategory', array($categories));

        return parent::removeCategory($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistrationForm(\Cx\Modules\Calendar\Model\Entity\RegistrationForm $registrationForm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistrationForm', array($registrationForm));

        return parent::setRegistrationForm($registrationForm);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationForm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationForm', array());

        return parent::getRegistrationForm();
    }

    /**
     * {@inheritDoc}
     */
    public function getComponentController()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComponentController', array());

        return parent::getComponentController();
    }

    /**
     * {@inheritDoc}
     */
    public function setVirtual($virtual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVirtual', array($virtual));

        return parent::setVirtual($virtual);
    }

    /**
     * {@inheritDoc}
     */
    public function isVirtual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isVirtual', array());

        return parent::isVirtual();
    }

    /**
     * {@inheritDoc}
     */
    public function initializeValidators()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'initializeValidators', array());

        return parent::initializeValidators();
    }

    /**
     * {@inheritDoc}
     */
    public function validate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'validate', array());

        return parent::validate();
    }

    /**
     * {@inheritDoc}
     */
    public function __call($methodName, $arguments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', array($methodName, $arguments));

        return parent::__call($methodName, $arguments);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
