<?php

namespace Cx\Model\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CxCore_ModulesSysLogModelEntityLogProxy extends \Cx\Core_Modules\SysLog\Model\Entity\Log implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setTimestamp($timestamp)
    {
        $this->_load();
        return parent::setTimestamp($timestamp);
    }

    public function getTimestamp()
    {
        $this->_load();
        return parent::getTimestamp();
    }

    public function setSeverity($severity)
    {
        $this->_load();
        return parent::setSeverity($severity);
    }

    public function getSeverity()
    {
        $this->_load();
        return parent::getSeverity();
    }

    public function setMessage($message)
    {
        $this->_load();
        return parent::setMessage($message);
    }

    public function getMessage()
    {
        $this->_load();
        return parent::getMessage();
    }

    public function setData($data)
    {
        $this->_load();
        return parent::setData($data);
    }

    public function getData()
    {
        $this->_load();
        return parent::getData();
    }

    public function setLogger($logger)
    {
        $this->_load();
        return parent::setLogger($logger);
    }

    public function getLogger()
    {
        $this->_load();
        return parent::getLogger();
    }

    public function __get($name)
    {
        $this->_load();
        return parent::__get($name);
    }

    public function getComponentController()
    {
        $this->_load();
        return parent::getComponentController();
    }

    public function setVirtual($virtual)
    {
        $this->_load();
        return parent::setVirtual($virtual);
    }

    public function isVirtual()
    {
        $this->_load();
        return parent::isVirtual();
    }

    public function validate()
    {
        $this->_load();
        return parent::validate();
    }

    public function __toString()
    {
        $this->_load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'timestamp', 'severity', 'message', 'data', 'logger');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}