<?php

namespace Cx\Model\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CxCore_ModulesAccessModelEntityAccessIdProxy extends \Cx\Core_Modules\Access\Model\Entity\AccessId implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setEntityClassName($entityClassName)
    {
        $this->_load();
        return parent::setEntityClassName($entityClassName);
    }

    public function getEntityClassName()
    {
        $this->_load();
        return parent::getEntityClassName();
    }

    public function setEntityClassId($entityClassId)
    {
        $this->_load();
        return parent::setEntityClassId($entityClassId);
    }

    public function getEntityClassId()
    {
        $this->_load();
        return parent::getEntityClassId();
    }

    public function addContrexxAccessUserAttribute(\Cx\Core\User\Model\Entity\UserAttribute $contrexxAccessUserAttribute)
    {
        $this->_load();
        return parent::addContrexxAccessUserAttribute($contrexxAccessUserAttribute);
    }

    public function getContrexxAccessUserAttribute()
    {
        $this->_load();
        return parent::getContrexxAccessUserAttribute();
    }

    public function addCoreAttribute(\Cx\Core\User\Model\Entity\CoreAttribute $coreAttribute)
    {
        $this->_load();
        return parent::addCoreAttribute($coreAttribute);
    }

    public function getCoreAttribute()
    {
        $this->_load();
        return parent::getCoreAttribute();
    }

    public function addGroup2(\Cx\Core\User\Model\Entity\Group $group2)
    {
        $this->_load();
        return parent::addGroup2($group2);
    }

    public function getGroup2()
    {
        $this->_load();
        return parent::getGroup2();
    }

    public function addGroup(\Cx\Core\User\Model\Entity\Group $group)
    {
        $this->_load();
        return parent::addGroup($group);
    }

    public function getGroup()
    {
        $this->_load();
        return parent::getGroup();
    }

    public function __get($name)
    {
        $this->_load();
        return parent::__get($name);
    }

    public function getComponentController()
    {
        $this->_load();
        return parent::getComponentController();
    }

    public function setVirtual($virtual)
    {
        $this->_load();
        return parent::setVirtual($virtual);
    }

    public function isVirtual()
    {
        $this->_load();
        return parent::isVirtual();
    }

    public function validate()
    {
        $this->_load();
        return parent::validate();
    }

    public function __toString()
    {
        $this->_load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'entity_class_name', 'entity_class_id', 'contrexxAccessUserAttribute', 'coreAttribute', 'group2', 'group');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}