<?php

namespace Cx\Model\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CxCore_ModulesSyncModelEntitySyncProxy extends \Cx\Core_Modules\Sync\Model\Entity\Sync implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setToUri($toUri)
    {
        $this->_load();
        return parent::setToUri($toUri);
    }

    public function getToUri($entityIndexData = array (
))
    {
        $this->_load();
        return parent::getToUri($entityIndexData);
    }

    public function setApiKey($apiKey)
    {
        $this->_load();
        return parent::setApiKey($apiKey);
    }

    public function getApiKey()
    {
        $this->_load();
        return parent::getApiKey();
    }

    public function setActive($active)
    {
        $this->_load();
        return parent::setActive($active);
    }

    public function setTempActive($tempActive)
    {
        $this->_load();
        return parent::setTempActive($tempActive);
    }

    public function getActive()
    {
        $this->_load();
        return parent::getActive();
    }

    public function setDataAccess(\Cx\Core_Modules\DataAccess\Model\Entity\DataAccess $dataAccess)
    {
        $this->_load();
        return parent::setDataAccess($dataAccess);
    }

    public function getDataAccess()
    {
        $this->_load();
        return parent::getDataAccess();
    }

    public function addRelation(\Cx\Core_Modules\Sync\Model\Entity\Relation $relation)
    {
        $this->_load();
        return parent::addRelation($relation);
    }

    public function getRelations()
    {
        $this->_load();
        return parent::getRelations();
    }

    public function setRelations($relations)
    {
        $this->_load();
        return parent::setRelations($relations);
    }

    public function addHostEntity(\Cx\Core_Modules\Sync\Model\Entity\HostEntity $hostEntity)
    {
        $this->_load();
        return parent::addHostEntity($hostEntity);
    }

    public function getHostEntities()
    {
        $this->_load();
        return parent::getHostEntities();
    }

    public function getHostEntitiesIncludingLegacy()
    {
        $this->_load();
        return parent::getHostEntitiesIncludingLegacy();
    }

    public function setOldHostEntitiesIncludingLegacy($hostEntities)
    {
        $this->_load();
        return parent::setOldHostEntitiesIncludingLegacy($hostEntities);
    }

    public function getOldHostEntitiesIncludingLegacy()
    {
        $this->_load();
        return parent::getOldHostEntitiesIncludingLegacy();
    }

    public function getRemovedHosts($entityIndexData)
    {
        $this->_load();
        return parent::getRemovedHosts($entityIndexData);
    }

    public function setHostEntities($hostEntities)
    {
        $this->_load();
        return parent::setHostEntities($hostEntities);
    }

    public function addChange(\Cx\Core_Modules\Sync\Model\Entity\Change $change)
    {
        $this->_load();
        return parent::addChange($change);
    }

    public function getChanges()
    {
        $this->_load();
        return parent::getChanges();
    }

    public function setChanges($changes)
    {
        $this->_load();
        return parent::setChanges($changes);
    }

    public function push($eventType, $entityIndexData, $entity)
    {
        $this->_load();
        return parent::push($eventType, $entityIndexData, $entity);
    }

    public function sendRequest($host, $content, $entityIndexData, $eventType)
    {
        $this->_load();
        return parent::sendRequest($host, $content, $entityIndexData, $eventType);
    }

    public function __get($name)
    {
        $this->_load();
        return parent::__get($name);
    }

    public function getComponentController()
    {
        $this->_load();
        return parent::getComponentController();
    }

    public function setVirtual($virtual)
    {
        $this->_load();
        return parent::setVirtual($virtual);
    }

    public function isVirtual()
    {
        $this->_load();
        return parent::isVirtual();
    }

    public function validate()
    {
        $this->_load();
        return parent::validate();
    }

    public function __toString()
    {
        $this->_load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'toUri', 'apiKey', 'active', 'relations', 'hostEntities', 'changes', 'dataAccess');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}