<?php

namespace Cx\Model\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CxModulesCalendarModelEntityEventProxy extends \Cx\Modules\Calendar\Model\Entity\Event implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setType($type)
    {
        $this->_load();
        return parent::setType($type);
    }

    public function getType()
    {
        $this->_load();
        return parent::getType();
    }

    public function setStartDate($startDate)
    {
        $this->_load();
        return parent::setStartDate($startDate);
    }

    public function getStartDate()
    {
        $this->_load();
        return parent::getStartDate();
    }

    public function setEndDate($endDate)
    {
        $this->_load();
        return parent::setEndDate($endDate);
    }

    public function getEndDate()
    {
        $this->_load();
        return parent::getEndDate();
    }

    public function setUseCustomDateDisplay($useCustomDateDisplay)
    {
        $this->_load();
        return parent::setUseCustomDateDisplay($useCustomDateDisplay);
    }

    public function getUseCustomDateDisplay()
    {
        $this->_load();
        return parent::getUseCustomDateDisplay();
    }

    public function setShowStartDateList($showStartDateList)
    {
        $this->_load();
        return parent::setShowStartDateList($showStartDateList);
    }

    public function getShowStartDateList()
    {
        $this->_load();
        return parent::getShowStartDateList();
    }

    public function setShowEndDateList($showEndDateList)
    {
        $this->_load();
        return parent::setShowEndDateList($showEndDateList);
    }

    public function getShowEndDateList()
    {
        $this->_load();
        return parent::getShowEndDateList();
    }

    public function setShowStartTimeList($showStartTimeList)
    {
        $this->_load();
        return parent::setShowStartTimeList($showStartTimeList);
    }

    public function getShowStartTimeList()
    {
        $this->_load();
        return parent::getShowStartTimeList();
    }

    public function setShowEndTimeList($showEndTimeList)
    {
        $this->_load();
        return parent::setShowEndTimeList($showEndTimeList);
    }

    public function getShowEndTimeList()
    {
        $this->_load();
        return parent::getShowEndTimeList();
    }

    public function setShowTimeTypeList($showTimeTypeList)
    {
        $this->_load();
        return parent::setShowTimeTypeList($showTimeTypeList);
    }

    public function getShowTimeTypeList()
    {
        $this->_load();
        return parent::getShowTimeTypeList();
    }

    public function setShowStartDateDetail($showStartDateDetail)
    {
        $this->_load();
        return parent::setShowStartDateDetail($showStartDateDetail);
    }

    public function getShowStartDateDetail()
    {
        $this->_load();
        return parent::getShowStartDateDetail();
    }

    public function setShowEndDateDetail($showEndDateDetail)
    {
        $this->_load();
        return parent::setShowEndDateDetail($showEndDateDetail);
    }

    public function getShowEndDateDetail()
    {
        $this->_load();
        return parent::getShowEndDateDetail();
    }

    public function setShowStartTimeDetail($showStartTimeDetail)
    {
        $this->_load();
        return parent::setShowStartTimeDetail($showStartTimeDetail);
    }

    public function getShowStartTimeDetail()
    {
        $this->_load();
        return parent::getShowStartTimeDetail();
    }

    public function setShowEndTimeDetail($showEndTimeDetail)
    {
        $this->_load();
        return parent::setShowEndTimeDetail($showEndTimeDetail);
    }

    public function getShowEndTimeDetail()
    {
        $this->_load();
        return parent::getShowEndTimeDetail();
    }

    public function setShowTimeTypeDetail($showTimeTypeDetail)
    {
        $this->_load();
        return parent::setShowTimeTypeDetail($showTimeTypeDetail);
    }

    public function getShowTimeTypeDetail()
    {
        $this->_load();
        return parent::getShowTimeTypeDetail();
    }

    public function setGoogle($google)
    {
        $this->_load();
        return parent::setGoogle($google);
    }

    public function getGoogle()
    {
        $this->_load();
        return parent::getGoogle();
    }

    public function setAccess($access)
    {
        $this->_load();
        return parent::setAccess($access);
    }

    public function getAccess()
    {
        $this->_load();
        return parent::getAccess();
    }

    public function setPriority($priority)
    {
        $this->_load();
        return parent::setPriority($priority);
    }

    public function getPriority()
    {
        $this->_load();
        return parent::getPriority();
    }

    public function setPrice($price)
    {
        $this->_load();
        return parent::setPrice($price);
    }

    public function getPrice()
    {
        $this->_load();
        return parent::getPrice();
    }

    public function setLink($link)
    {
        $this->_load();
        return parent::setLink($link);
    }

    public function getLink()
    {
        $this->_load();
        return parent::getLink();
    }

    public function setPic($pic)
    {
        $this->_load();
        return parent::setPic($pic);
    }

    public function getPic()
    {
        $this->_load();
        return parent::getPic();
    }

    public function setAttach($attach)
    {
        $this->_load();
        return parent::setAttach($attach);
    }

    public function getAttach()
    {
        $this->_load();
        return parent::getAttach();
    }

    public function setPlaceMediadirId($placeMediadirId)
    {
        $this->_load();
        return parent::setPlaceMediadirId($placeMediadirId);
    }

    public function getPlaceMediadirId()
    {
        $this->_load();
        return parent::getPlaceMediadirId();
    }

    public function setShowIn($showIn)
    {
        $this->_load();
        return parent::setShowIn($showIn);
    }

    public function getShowIn()
    {
        $this->_load();
        return parent::getShowIn();
    }

    public function setInvitedGroups($invitedGroups)
    {
        $this->_load();
        return parent::setInvitedGroups($invitedGroups);
    }

    public function getInvitedGroups()
    {
        $this->_load();
        return parent::getInvitedGroups();
    }

    public function setInvitedMails($invitedMails)
    {
        $this->_load();
        return parent::setInvitedMails($invitedMails);
    }

    public function getInvitedMails()
    {
        $this->_load();
        return parent::getInvitedMails();
    }

    public function setInvitationSent($invitationSent)
    {
        $this->_load();
        return parent::setInvitationSent($invitationSent);
    }

    public function getInvitationSent()
    {
        $this->_load();
        return parent::getInvitationSent();
    }

    public function setInvitationEmailTemplate($invitationEmailTemplate)
    {
        $this->_load();
        return parent::setInvitationEmailTemplate($invitationEmailTemplate);
    }

    public function getInvitationEmailTemplate()
    {
        $this->_load();
        return parent::getInvitationEmailTemplate();
    }

    public function setRegistration($registration)
    {
        $this->_load();
        return parent::setRegistration($registration);
    }

    public function getRegistration()
    {
        $this->_load();
        return parent::getRegistration();
    }

    public function setRegistrationNum($registrationNum)
    {
        $this->_load();
        return parent::setRegistrationNum($registrationNum);
    }

    public function getRegistrationNum()
    {
        $this->_load();
        return parent::getRegistrationNum();
    }

    public function setRegistrationNotification($registrationNotification)
    {
        $this->_load();
        return parent::setRegistrationNotification($registrationNotification);
    }

    public function getRegistrationNotification()
    {
        $this->_load();
        return parent::getRegistrationNotification();
    }

    public function setEmailTemplate($emailTemplate)
    {
        $this->_load();
        return parent::setEmailTemplate($emailTemplate);
    }

    public function getEmailTemplate()
    {
        $this->_load();
        return parent::getEmailTemplate();
    }

    public function getMail($mailString)
    {
        $this->_load();
        return parent::getMail($mailString);
    }

    public function setTicketSales($ticketSales)
    {
        $this->_load();
        return parent::setTicketSales($ticketSales);
    }

    public function getTicketSales()
    {
        $this->_load();
        return parent::getTicketSales();
    }

    public function setNumSeating($numSeating)
    {
        $this->_load();
        return parent::setNumSeating($numSeating);
    }

    public function getNumSeating()
    {
        $this->_load();
        return parent::getNumSeating();
    }

    public function setSeriesStatus($seriesStatus)
    {
        $this->_load();
        return parent::setSeriesStatus($seriesStatus);
    }

    public function getSeriesStatus()
    {
        $this->_load();
        return parent::getSeriesStatus();
    }

    public function setSeriesType($seriesType)
    {
        $this->_load();
        return parent::setSeriesType($seriesType);
    }

    public function getSeriesType()
    {
        $this->_load();
        return parent::getSeriesType();
    }

    public function setSeriesPatternCount($seriesPatternCount)
    {
        $this->_load();
        return parent::setSeriesPatternCount($seriesPatternCount);
    }

    public function getSeriesPatternCount()
    {
        $this->_load();
        return parent::getSeriesPatternCount();
    }

    public function setSeriesPatternWeekday($seriesPatternWeekday)
    {
        $this->_load();
        return parent::setSeriesPatternWeekday($seriesPatternWeekday);
    }

    public function getSeriesPatternWeekday()
    {
        $this->_load();
        return parent::getSeriesPatternWeekday();
    }

    public function setSeriesPatternDay($seriesPatternDay)
    {
        $this->_load();
        return parent::setSeriesPatternDay($seriesPatternDay);
    }

    public function getSeriesPatternDay()
    {
        $this->_load();
        return parent::getSeriesPatternDay();
    }

    public function setSeriesPatternWeek($seriesPatternWeek)
    {
        $this->_load();
        return parent::setSeriesPatternWeek($seriesPatternWeek);
    }

    public function getSeriesPatternWeek()
    {
        $this->_load();
        return parent::getSeriesPatternWeek();
    }

    public function setSeriesPatternMonth($seriesPatternMonth)
    {
        $this->_load();
        return parent::setSeriesPatternMonth($seriesPatternMonth);
    }

    public function getSeriesPatternMonth()
    {
        $this->_load();
        return parent::getSeriesPatternMonth();
    }

    public function setSeriesPatternType($seriesPatternType)
    {
        $this->_load();
        return parent::setSeriesPatternType($seriesPatternType);
    }

    public function getSeriesPatternType()
    {
        $this->_load();
        return parent::getSeriesPatternType();
    }

    public function setSeriesPatternDouranceType($seriesPatternDouranceType)
    {
        $this->_load();
        return parent::setSeriesPatternDouranceType($seriesPatternDouranceType);
    }

    public function getSeriesPatternDouranceType()
    {
        $this->_load();
        return parent::getSeriesPatternDouranceType();
    }

    public function setSeriesPatternEnd($seriesPatternEnd)
    {
        $this->_load();
        return parent::setSeriesPatternEnd($seriesPatternEnd);
    }

    public function getSeriesPatternEnd()
    {
        $this->_load();
        return parent::getSeriesPatternEnd();
    }

    public function setSeriesPatternEndDate($seriesPatternEndDate)
    {
        $this->_load();
        return parent::setSeriesPatternEndDate($seriesPatternEndDate);
    }

    public function getSeriesPatternEndDate()
    {
        $this->_load();
        return parent::getSeriesPatternEndDate();
    }

    public function setSeriesPatternBegin($seriesPatternBegin)
    {
        $this->_load();
        return parent::setSeriesPatternBegin($seriesPatternBegin);
    }

    public function getSeriesPatternBegin()
    {
        $this->_load();
        return parent::getSeriesPatternBegin();
    }

    public function setSeriesPatternExceptions($seriesPatternExceptions)
    {
        $this->_load();
        return parent::setSeriesPatternExceptions($seriesPatternExceptions);
    }

    public function getSeriesPatternExceptions()
    {
        $this->_load();
        return parent::getSeriesPatternExceptions();
    }

    public function setStatus($status)
    {
        $this->_load();
        return parent::setStatus($status);
    }

    public function getStatus()
    {
        $this->_load();
        return parent::getStatus();
    }

    public function setConfirmed($confirmed)
    {
        $this->_load();
        return parent::setConfirmed($confirmed);
    }

    public function getConfirmed()
    {
        $this->_load();
        return parent::getConfirmed();
    }

    public function setShowDetailView($showDetailView)
    {
        $this->_load();
        return parent::setShowDetailView($showDetailView);
    }

    public function getShowDetailView()
    {
        $this->_load();
        return parent::getShowDetailView();
    }

    public function setAuthor($author)
    {
        $this->_load();
        return parent::setAuthor($author);
    }

    public function getAuthor()
    {
        $this->_load();
        return parent::getAuthor();
    }

    public function setAllDay($allDay)
    {
        $this->_load();
        return parent::setAllDay($allDay);
    }

    public function getAllDay()
    {
        $this->_load();
        return parent::getAllDay();
    }

    public function setLocationType($locationType)
    {
        $this->_load();
        return parent::setLocationType($locationType);
    }

    public function getLocationType()
    {
        $this->_load();
        return parent::getLocationType();
    }

    public function setPlaceId($placeId)
    {
        $this->_load();
        return parent::setPlaceId($placeId);
    }

    public function getPlaceId()
    {
        $this->_load();
        return parent::getPlaceId();
    }

    public function setPlaceStreet($placeStreet)
    {
        $this->_load();
        return parent::setPlaceStreet($placeStreet);
    }

    public function getPlaceStreet()
    {
        $this->_load();
        return parent::getPlaceStreet();
    }

    public function setPlaceZip($placeZip)
    {
        $this->_load();
        return parent::setPlaceZip($placeZip);
    }

    public function getPlaceZip()
    {
        $this->_load();
        return parent::getPlaceZip();
    }

    public function setPlaceLink($placeLink)
    {
        $this->_load();
        return parent::setPlaceLink($placeLink);
    }

    public function getPlaceLink()
    {
        $this->_load();
        return parent::getPlaceLink();
    }

    public function setPlaceMap($placeMap)
    {
        $this->_load();
        return parent::setPlaceMap($placeMap);
    }

    public function getPlaceMap()
    {
        $this->_load();
        return parent::getPlaceMap();
    }

    public function setHostType($hostType)
    {
        $this->_load();
        return parent::setHostType($hostType);
    }

    public function getHostType()
    {
        $this->_load();
        return parent::getHostType();
    }

    public function setOrgStreet($orgStreet)
    {
        $this->_load();
        return parent::setOrgStreet($orgStreet);
    }

    public function getOrgStreet()
    {
        $this->_load();
        return parent::getOrgStreet();
    }

    public function setOrgZip($orgZip)
    {
        $this->_load();
        return parent::setOrgZip($orgZip);
    }

    public function getOrgZip()
    {
        $this->_load();
        return parent::getOrgZip();
    }

    public function setOrgLink($orgLink)
    {
        $this->_load();
        return parent::setOrgLink($orgLink);
    }

    public function getOrgLink()
    {
        $this->_load();
        return parent::getOrgLink();
    }

    public function setOrgEmail($orgEmail)
    {
        $this->_load();
        return parent::setOrgEmail($orgEmail);
    }

    public function getOrgEmail()
    {
        $this->_load();
        return parent::getOrgEmail();
    }

    public function setHostMediadirId($hostMediadirId)
    {
        $this->_load();
        return parent::setHostMediadirId($hostMediadirId);
    }

    public function getHostMediadirId()
    {
        $this->_load();
        return parent::getHostMediadirId();
    }

    public function setRegistrationExternalLink($registrationExternalLink)
    {
        $this->_load();
        return parent::setRegistrationExternalLink($registrationExternalLink);
    }

    public function getRegistrationExternalLink()
    {
        $this->_load();
        return parent::getRegistrationExternalLink();
    }

    public function setRegistrationExternalFullyBooked($registrationExternalFullyBooked)
    {
        $this->_load();
        return parent::setRegistrationExternalFullyBooked($registrationExternalFullyBooked);
    }

    public function getRegistrationExternalFullyBooked()
    {
        $this->_load();
        return parent::getRegistrationExternalFullyBooked();
    }

    public function addEventField(\Cx\Modules\Calendar\Model\Entity\EventField $eventField)
    {
        $this->_load();
        return parent::addEventField($eventField);
    }

    public function setEventFields($eventFields)
    {
        $this->_load();
        return parent::setEventFields($eventFields);
    }

    public function getEventFieldByLangId($langId)
    {
        $this->_load();
        return parent::getEventFieldByLangId($langId);
    }

    public function getEventFields()
    {
        $this->_load();
        return parent::getEventFields();
    }

    public function addRegistration(\Cx\Modules\Calendar\Model\Entity\Registration $registration)
    {
        $this->_load();
        return parent::addRegistration($registration);
    }

    public function setRegistrations($registrations)
    {
        $this->_load();
        return parent::setRegistrations($registrations);
    }

    public function getRegistrations()
    {
        $this->_load();
        return parent::getRegistrations();
    }

    public function setCategory(\Cx\Modules\Calendar\Model\Entity\Category $category)
    {
        $this->_load();
        return parent::setCategory($category);
    }

    public function getCategory()
    {
        $this->_load();
        return parent::getCategory();
    }

    public function setRegistrationForm(\Cx\Modules\Calendar\Model\Entity\RegistrationForm $registrationForm)
    {
        $this->_load();
        return parent::setRegistrationForm($registrationForm);
    }

    public function getRegistrationForm()
    {
        $this->_load();
        return parent::getRegistrationForm();
    }

    public function __get($name)
    {
        $this->_load();
        return parent::__get($name);
    }

    public function getComponentController()
    {
        $this->_load();
        return parent::getComponentController();
    }

    public function setVirtual($virtual)
    {
        $this->_load();
        return parent::setVirtual($virtual);
    }

    public function isVirtual()
    {
        $this->_load();
        return parent::isVirtual();
    }

    public function validate()
    {
        $this->_load();
        return parent::validate();
    }

    public function __toString()
    {
        $this->_load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'type', 'startDate', 'endDate', 'useCustomDateDisplay', 'showStartDateList', 'showEndDateList', 'showStartTimeList', 'showEndTimeList', 'showTimeTypeList', 'showStartDateDetail', 'showEndDateDetail', 'showStartTimeDetail', 'showEndTimeDetail', 'showTimeTypeDetail', 'google', 'access', 'priority', 'price', 'link', 'pic', 'attach', 'placeMediadirId', 'showIn', 'invitedGroups', 'invitedMails', 'invitationSent', 'invitationEmailTemplate', 'registration', 'registrationNum', 'registrationNotification', 'emailTemplate', 'ticketSales', 'numSeating', 'seriesStatus', 'seriesType', 'seriesPatternCount', 'seriesPatternWeekday', 'seriesPatternDay', 'seriesPatternWeek', 'seriesPatternMonth', 'seriesPatternType', 'seriesPatternDouranceType', 'seriesPatternEnd', 'seriesPatternEndDate', 'seriesPatternBegin', 'seriesPatternExceptions', 'status', 'confirmed', 'showDetailView', 'author', 'allDay', 'locationType', 'placeId', 'placeStreet', 'placeZip', 'placeLink', 'placeMap', 'hostType', 'orgStreet', 'orgZip', 'orgLink', 'orgEmail', 'hostMediadirId', 'registrationExternalLink', 'registrationExternalFullyBooked', 'eventFields', 'registrations', 'category', 'registrationForm');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}