<?php

namespace Cx\Model\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CxModulesMediaDirModelEntityLevelProxy extends \Cx\Modules\MediaDir\Model\Entity\Level implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setOrder($order)
    {
        $this->_load();
        return parent::setOrder($order);
    }

    public function getOrder()
    {
        $this->_load();
        return parent::getOrder();
    }

    public function setShowSublevels($showSublevels)
    {
        $this->_load();
        return parent::setShowSublevels($showSublevels);
    }

    public function getShowSublevels()
    {
        $this->_load();
        return parent::getShowSublevels();
    }

    public function setShowCategories($showCategories)
    {
        $this->_load();
        return parent::setShowCategories($showCategories);
    }

    public function getShowCategories()
    {
        $this->_load();
        return parent::getShowCategories();
    }

    public function setShowEntries($showEntries)
    {
        $this->_load();
        return parent::setShowEntries($showEntries);
    }

    public function getShowEntries()
    {
        $this->_load();
        return parent::getShowEntries();
    }

    public function setPicture($picture)
    {
        $this->_load();
        return parent::setPicture($picture);
    }

    public function getPicture()
    {
        $this->_load();
        return parent::getPicture();
    }

    public function setActive($active)
    {
        $this->_load();
        return parent::setActive($active);
    }

    public function getActive()
    {
        $this->_load();
        return parent::getActive();
    }

    public function setLft($lft)
    {
        $this->_load();
        return parent::setLft($lft);
    }

    public function getLft()
    {
        $this->_load();
        return parent::getLft();
    }

    public function setRgt($rgt)
    {
        $this->_load();
        return parent::setRgt($rgt);
    }

    public function getRgt()
    {
        $this->_load();
        return parent::getRgt();
    }

    public function setLvl($lvl)
    {
        $this->_load();
        return parent::setLvl($lvl);
    }

    public function getLvl()
    {
        $this->_load();
        return parent::getLvl();
    }

    public function addChildren(\Cx\Modules\MediaDir\Model\Entity\Level $children)
    {
        $this->_load();
        return parent::addChildren($children);
    }

    public function getChildren()
    {
        $this->_load();
        return parent::getChildren();
    }

    public function addLocale(\Cx\Modules\MediaDir\Model\Entity\LevelLocale $locale)
    {
        $this->_load();
        return parent::addLocale($locale);
    }

    public function getLocale()
    {
        $this->_load();
        return parent::getLocale();
    }

    public function getLocaleByLang($lang = NULL)
    {
        $this->_load();
        return parent::getLocaleByLang($lang);
    }

    public function setParent(\Cx\Modules\MediaDir\Model\Entity\Level $parent)
    {
        $this->_load();
        return parent::setParent($parent);
    }

    public function getParent()
    {
        $this->_load();
        return parent::getParent();
    }

    public function __get($name)
    {
        $this->_load();
        return parent::__get($name);
    }

    public function getComponentController()
    {
        $this->_load();
        return parent::getComponentController();
    }

    public function setVirtual($virtual)
    {
        $this->_load();
        return parent::setVirtual($virtual);
    }

    public function isVirtual()
    {
        $this->_load();
        return parent::isVirtual();
    }

    public function validate()
    {
        $this->_load();
        return parent::validate();
    }

    public function __toString()
    {
        $this->_load();
        return parent::__toString();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'order', 'show_sublevels', 'show_categories', 'show_entries', 'picture', 'active', 'lft', 'rgt', 'lvl', 'children', 'locale', 'parent');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}