INSERT INTO `contrexx_modules` ( `id` , `name` , `description_variable` , `status` , `is_required` , `is_core` ) VALUES ( 35 , 'podcast', 'TXT_PODCAST_MODULE_DESCRIPTION', 'y', '0', '0');

INSERT INTO `contrexx_backend_areas` ( `area_id` , `parent_area_id` , `type` , `area_name` , `is_active` , `uri` , `target` , `module_id` , `order_id` , `access_id` )
VALUES (
NULL , '2', 'navigation', 'TXT_PODCAST', '1', 'index.php?cmd=podcast', '_self', '35', '17', '87'
);



-- 
-- Tabellenstruktur für Tabelle `contrexx_module_podcast_category`
-- 

CREATE TABLE `contrexx_module_podcast_category` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `title` varchar(255) NOT NULL default '',
  `description` varchar(255) NOT NULL default '',
  `status` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`id`)
) TYPE=MyISAM;

-- --------------------------------------------------------

-- 
-- Tabellenstruktur für Tabelle `contrexx_module_podcast_medium`
-- 

CREATE TABLE `contrexx_module_podcast_medium` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `title` varchar(255) NOT NULL default '',
  `author` varchar(255) NOT NULL default '',
  `description` text NOT NULL,
  `source` text NOT NULL,
  `template_id` int(11) unsigned NOT NULL default '0',
  `width` int(10) unsigned default NULL,
  `height` int(10) unsigned default NULL,
  `playlenght` int(10) unsigned NOT NULL default '0',
  `status` tinyint(1) NOT NULL default '0',
  `date_added` int(14) unsigned NOT NULL default '0',
  PRIMARY KEY  (`id`)
) TYPE=MyISAM;

-- --------------------------------------------------------

-- 
-- Tabellenstruktur für Tabelle `contrexx_module_podcast_rel_category_lang`
-- 

CREATE TABLE `contrexx_module_podcast_rel_category_lang` (
  `category_id` int(10) unsigned NOT NULL default '0',
  `lang_id` int(10) unsigned NOT NULL default '0'
) TYPE=MyISAM;

-- --------------------------------------------------------

-- 
-- Tabellenstruktur für Tabelle `contrexx_module_podcast_rel_medium_category`
-- 

CREATE TABLE `contrexx_module_podcast_rel_medium_category` (
  `medium_id` int(10) unsigned NOT NULL default '0',
  `category_id` int(10) unsigned NOT NULL default '0'
) TYPE=MyISAM;

-- --------------------------------------------------------

-- 
-- Tabellenstruktur für Tabelle `contrexx_module_podcast_template`
-- 

CREATE TABLE `contrexx_module_podcast_template` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `description` varchar(255) NOT NULL default '',
  `template` text NOT NULL,
  `extensions` varchar(255) NOT NULL default '',
  PRIMARY KEY  (`id`),
  UNIQUE KEY `description` (`description`)
) TYPE=MyISAM;


-- 
-- Daten für Tabelle `contrexx_module_podcast_template`
-- 

INSERT INTO `contrexx_module_podcast_template` VALUES (1, 'Video für Windows (Windows Media Player Plug-in)', '<object id="podcastPlayer" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" classid="CLSID:6BF52A52-394A-11d3-B153-00C04F79FAA6" codebase="http://activex.microsoft.com/activex/controls/mplayer/en/nsmp2inf.cab#Version=6,0,02,902" standby="Loading Microsoft Windows Media Player components...">\r\n<param name="FileName" value="[[MEDIUM_URL]]" />\r\n<param name="animationatStart" value="true" />\r\n<param name="transparentatStart" value="true" />\r\n<param name="autoStart" value="true" />\r\n<param name="showControls" value="true" />\r\n<param name="type" value="application/x-oleobject" />\r\n<embed type="application/x-mplayer2" pluginspage="http://www.microsoft.com/Windows/MediaPlayer/" src="[[MEDIUM_URL]]" name="podcastPlayer" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" AutoStart="true">\r\n</embed>\r\n</object>', 'avi, wmv');
INSERT INTO `contrexx_module_podcast_template` VALUES (2, 'RealMedia (RealMedia Player Plug-in)', '<object id="podcastPlayer1" classid="clsid:CFCDAA03-8BE4-11cf-B84B-0020AFBBCCFA" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]">\r\n<param name="controls" value="all">\r\n<param name="autostart" value="true">\r\n<embed src="[[MEDIUM_URL]]" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" autostart="true" type="video/x-pn-realvideo" console="video1" controls="All" nojava="true"></embed>\r\n</object>', 'ram, rpm');
INSERT INTO `contrexx_module_podcast_template` VALUES (5, 'QuickTime Film (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="video/quicktime" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="video/quicktime" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'mov, qt, mqv');
INSERT INTO `contrexx_module_podcast_template` VALUES (6, 'CAF-Audio (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="audio/x-caf" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="audio/x-caf" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'caf');
INSERT INTO `contrexx_module_podcast_template` VALUES (7, 'AAC-Audio (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="audio/x-aac" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="audio/x-aac" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'aac, adts');
INSERT INTO `contrexx_module_podcast_template` VALUES (8, 'AMR-Audio (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="audio/AMR" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="audio/AMR" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'amr');
INSERT INTO `contrexx_module_podcast_template` VALUES (9, 'GSM-Audio (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="audio/x-gsm" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="audio/x-gsm" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'gsm');
INSERT INTO `contrexx_module_podcast_template` VALUES (10, 'QUALCOMM PureVoice Audio (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="audio/vnd.qcelp" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="audio/vnd.qcelp" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'qcp');
INSERT INTO `contrexx_module_podcast_template` VALUES (11, 'MIDI (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="audio/x-midi" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="audio/x-midi" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'mid, midi, smf, kar');
INSERT INTO `contrexx_module_podcast_template` VALUES (12, 'uLaw/AU-Audio (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="audio/basic" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="audio/basic" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'au, snd, ulw');
INSERT INTO `contrexx_module_podcast_template` VALUES (13, 'AIFF-Audio (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="audio/x-aiff" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="audio/x-aiff" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'aiff, aif, aifc, cdda');
INSERT INTO `contrexx_module_podcast_template` VALUES (14, 'WAVE-Audio (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="audio/x-wav" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="audio/x-wav" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'wav, bwf');
INSERT INTO `contrexx_module_podcast_template` VALUES (15, 'Video für Windows (AVI) (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="video/x-msvideo" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="video/x-msvideo" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'avi, vfw');
INSERT INTO `contrexx_module_podcast_template` VALUES (16, 'AutoDesk Animator (FLC) (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="video/flc" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="video/flc" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'flc, fli, cel');
INSERT INTO `contrexx_module_podcast_template` VALUES (17, 'Digitales Video (DV) (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="video/x-dv" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="video/x-dv" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'dv, dif');
INSERT INTO `contrexx_module_podcast_template` VALUES (18, 'SDP-Stream-Beschreibung (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="application/x-sdp" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="application/x-sdp" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'sdp');
INSERT INTO `contrexx_module_podcast_template` VALUES (19, 'RTSP-Stream-Beschreibung (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="application/x-rtsp" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="application/x-rtsp" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'rtsp, rts');
INSERT INTO `contrexx_module_podcast_template` VALUES (20, 'MP3-Wiedergabeliste (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="audio/x-mpegurl" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="audio/x-mpegurl" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'm3u, m3url');
INSERT INTO `contrexx_module_podcast_template` VALUES (21, 'MPEG-Medien (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="video/x-mpeg" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="video/x-mpeg" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'mpeg, mpg, m1s, m1v, m1a, m75, m15, mp2');
INSERT INTO `contrexx_module_podcast_template` VALUES (22, '3GPP-Medien (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="video/3gpp" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="video/3gpp" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', '3gp, 3gpp');
INSERT INTO `contrexx_module_podcast_template` VALUES (23, '3GPP2-Medien (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="video/3gpp2" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="video/3gpp2" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', '3g2, 3gp2');
INSERT INTO `contrexx_module_podcast_template` VALUES (24, 'SD-Video (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="video/sd-video" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="video/sd-video" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'sdv');
INSERT INTO `contrexx_module_podcast_template` VALUES (25, 'AMC-Medien (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="application/x-mpeg" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="application/x-mpeg" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'amc');
INSERT INTO `contrexx_module_podcast_template` VALUES (26, 'MPEG-4-Medien (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="video/mp4" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="video/mp4" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'mp4');
INSERT INTO `contrexx_module_podcast_template` VALUES (27, 'AAC-Audiodatei (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="audio/x-m4a" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="audio/x-m4a" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'm4a');
INSERT INTO `contrexx_module_podcast_template` VALUES (28, 'AAC-Audio (geschützt) (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="audio/x-m4p" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="audio/x-m4p" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'm4p');
INSERT INTO `contrexx_module_podcast_template` VALUES (29, 'ACC-Audiobuch (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="audio/x-m4b" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="audio/x-m4b" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'm4b');
INSERT INTO `contrexx_module_podcast_template` VALUES (30, 'Video (geschützt) (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="video/x-m4v" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="video/x-m4v" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'm4v');
INSERT INTO `contrexx_module_podcast_template` VALUES (31, 'MP3-Audio (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="audio/x-mpeg" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="audio/x-mpeg" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'mp3, swa');
INSERT INTO `contrexx_module_podcast_template` VALUES (32, 'Sound Designer II (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="audio/x-sd2" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="audio/x-sd2" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'sd2');
INSERT INTO `contrexx_module_podcast_template` VALUES (33, 'BMP-Bild (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="image/x-bmp" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="image/x-bmp" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'bmp, dib');
INSERT INTO `contrexx_module_podcast_template` VALUES (34, 'MacPaint Bild (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="image/x-macpaint" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="image/x-macpaint" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'pntg, pnt, mac');
INSERT INTO `contrexx_module_podcast_template` VALUES (35, 'PICT-Bild (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="image/x-pict" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="image/x-pict" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'pict, pic, pct');
INSERT INTO `contrexx_module_podcast_template` VALUES (36, 'PNG-Bild (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="image/x-png" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="image/x-png" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'png');
INSERT INTO `contrexx_module_podcast_template` VALUES (37, 'QuickTime Bild (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="image/x-quicktime" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="image/x-quicktime" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'qtif, qti');
INSERT INTO `contrexx_module_podcast_template` VALUES (38, 'SGI-Bild (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="image/x-sgi" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="image/x-sgi" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'sgi, rgb');
INSERT INTO `contrexx_module_podcast_template` VALUES (39, 'TGA-Bild (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="image/x-targa" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="image/x-targa" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'targa, tga');
INSERT INTO `contrexx_module_podcast_template` VALUES (40, 'TIFF-Bild (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="image/x-tiff" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="image/x-tiff" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'tif, tiff');
INSERT INTO `contrexx_module_podcast_template` VALUES (41, 'Photoshop-Bild (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="image/x-photoshop" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="image/x-photoshop" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'psd');
INSERT INTO `contrexx_module_podcast_template` VALUES (42, 'JPEG2000 image (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="image/jp2" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="image/jp2" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'jp2');
INSERT INTO `contrexx_module_podcast_template` VALUES (43, 'SMIL 1.0 (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="application/smil" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="application/smil" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'smi, sml, smil');
INSERT INTO `contrexx_module_podcast_template` VALUES (44, 'Flash-Medien (QuckTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="application/x-shockwave-flash" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="application/x-shockwave-flash" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'swf');
INSERT INTO `contrexx_module_podcast_template` VALUES (45, 'QuickTime HTML (QHTML) (QuickTime Plug-in)', '<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="autoplay" value="true" />\r\n<param name="controller" value="true" />\r\n<param name="target" value="myself" />\r\n<param name="type" value="text/x-html-insertion" />\r\n<embed src="[[MEDIUM_URL]]" width=[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" type="text/x-html-insertion" pluginspage="http://www.apple.com/quicktime/download/" autoplay="true" controller="true" target="myself" />\r\n</object>', 'qht, qhtm');
INSERT INTO `contrexx_module_podcast_template` VALUES (46, 'MP3-Audio (RealPlayer Player)', '<object id="videoplayer1" classid="clsid:CFCDAA03-8BE4-11cf-B84B-0020AFBBCCFA" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="controls" value="all" />\r\n<param name="autostart" value="true" />\r\n<param name="type" value="audio/x-mpeg" />\r\n<embed src="[[MEDIUM_URL]]" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" autostart="true" type="audio/x-mpeg" console="video1" controls="All" nojava="true"></embed>\r\n</object>', 'mp3');
INSERT INTO `contrexx_module_podcast_template` VALUES (47, 'MP3-Wiedergabeliste (RealPlayer Plug-in)', '<object id="videoplayer1" classid="clsid:CFCDAA03-8BE4-11cf-B84B-0020AFBBCCFA" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="controls" value="all" />\r\n<param name="autostart" value="true" />\r\n<param name="type" value="audio/x-mpegurl" />\r\n<embed src="[[MEDIUM_URL]]" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" autostart="true" type="audio/x-mpegurl" console="video1" controls="All" nojava="true"></embed>\r\n</object>', 'm3u, m3url');
INSERT INTO `contrexx_module_podcast_template` VALUES (48, 'WAVE-Audio (RealPlayer Plug-in)', '<object id="videoplayer1" classid="clsid:CFCDAA03-8BE4-11cf-B84B-0020AFBBCCFA" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]">\r\n<param name="src" value="[[MEDIUM_URL]]" />\r\n<param name="controls" value="all" />\r\n<param name="autostart" value="true" />\r\n<param name="type" value="audio/x-wav" />\r\n<embed src="[[MEDIUM_URL]]" width="[[MEDIUM_WIDTH]]" height="[[MEDIUM_HEIGHT]]" autostart="true" type="audio/x-wav" console="video1" controls="All" nojava="true"></embed>\r\n</object>', 'wav');


CREATE TABLE `contrexx_module_podcast_settings` (
  `setid` smallint(6) NOT NULL auto_increment,
  `setname` varchar(250) NOT NULL default '',
  `setvalue` text NOT NULL,
  `status` tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (`setid`)
) TYPE=MyISAM;

INSERT INTO `contrexx_module_podcast_settings` ( `setid` , `setname` , `setvalue` , `status` )
VALUES (
NULL , 'default_width', '320', '1'
), (
NULL , 'default_height', '240', '1'
);