<?php

namespace Cx\Modules\FavoriteList\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FavoriteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriteRepository extends EntityRepository
{
}
