<?php
<<<<<<< HEAD

/**
 * Contrexx
 *
 * @link      http://www.contrexx.com
 * @copyright Comvation AG 2007-2014
 * @version   Contrexx 4.0
 * 
 * According to our dual licensing model, this program can be used either
 * under the terms of the GNU Affero General Public License, version 3,
 * or under a proprietary license.
 *
 * The texts of the GNU Affero General Public License with an additional
 * permission and of our proprietary license can be found at and
 * in the LICENSE file you have received along with this program.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * "Contrexx" is a registered trademark of Comvation AG.
 * The licensing of the program under the AGPLv3 does not imply a
 * trademark license. Therefore any rights, title and interest in
 * our trademarks remain entirely with us.
 */

=======
>>>>>>> f7ee35166c3ea0314d3113cfac8fc8894c4d0211
/**
* This file is generated by the "settings"-menu in your CMS.
* Do not try to edit it manually!
*/

/**
* -------------------------------------------------------------------------
* Core
* -------------------------------------------------------------------------
*/
<<<<<<< HEAD
$_CONFIG['cacheDbStatus']                = "off";
$_CONFIG['cacheEnabled']                 = "off";
$_CONFIG['cacheExpiration']              = 86400;
$_CONFIG['cacheOPCache']                 = "off";
$_CONFIG['cacheOpStatus']                = "off";
$_CONFIG['cacheProxyCacheVarnishConfig'] = "{\"ip\":\"127.0.0.1\",\"port\":\"8080\"}";
$_CONFIG['cacheUserCache']               = "off";
$_CONFIG['cacheUserCacheMemcacheConfig'] = "{\"ip\":\"127.0.0.1\",\"port\":11211}";
$_CONFIG['cacheVarnishStatus']           = "off";
$_CONFIG['contactAddress']               = "Musterstrasse 12";
$_CONFIG['contactCompany']               = "Ihr Firmenname";
$_CONFIG['contactCountry']               = "Musterland";
$_CONFIG['contactFax']                   = "033 123 45 68";
$_CONFIG['contactPhone']                 = "033 123 45 67";
$_CONFIG['contactPlace']                 = "Musterhausen";
$_CONFIG['contactZip']                   = 3600;
$_CONFIG['coreAdminEmail']               = "info@example.com";
$_CONFIG['coreAdminName']                = "Administrator";
$_CONFIG['coreGlobalPageTitle']          = "Default Installation";
$_CONFIG['coreIdsStatus']                = "off";
$_CONFIG['coreListProtectedPages']       = "off";
$_CONFIG['corePagingLimit']              = 30;
$_CONFIG['coreSmtpServer']               = 0;
$_CONFIG['dashboardNews']                = "on";
$_CONFIG['dashboardStatistics']          = "on";
$_CONFIG['dnsServer']                    = "ns1.contrexxhosting.com";
$_CONFIG['domainUrl']                    = "contrexx3.dev";
$_CONFIG['forceDomainUrl']               = "off";
$_CONFIG['forceProtocolBackend']         = "none";
$_CONFIG['forceProtocolFrontend']        = "none";
$_CONFIG['frontendEditingStatus']        = "on";
$_CONFIG['googleAnalyticsTrackingId']    = "";
$_CONFIG['googleMapsAPIKey']             = "";
$_CONFIG['installationId']               = "CONTREXX_4_0_4cc9e83119af6520568b2683267";
$_CONFIG['languageDetection']            = "on";
$_CONFIG['lastAccessId']                 = 382;
$_CONFIG['licenseKey']                   = "CONTREXX_4_0_35bcf29a638c37735c5c8f61b8f";
$_CONFIG['passwordComplexity']           = "off";
$_CONFIG['searchVisibleContentOnly']     = "on";
$_CONFIG['sessionLifeTime']              = 3600;
$_CONFIG['sessionLifeTimeRememberMe']    = 1209600;
$_CONFIG['spamKeywords']                 = "sex, viagra";
$_CONFIG['systemStatus']                 = "on";
$_CONFIG['timezone']                     = "Europe/Zurich";
$_CONFIG['useCustomizings']              = "off";
$_CONFIG['xmlSitemapStatus']             = "on";
=======
$_CONFIG['cacheEnabled']              = "off";
$_CONFIG['cacheExpiration']           = 86400;
$_CONFIG['contactAddress']            = "Musterstrasse 12";
$_CONFIG['contactCompany']            = "Ihr Firmenname";
$_CONFIG['contactCountry']            = "Musterland";
$_CONFIG['contactFax']                = "033 123 45 68";
$_CONFIG['contactPhone']              = "033 123 45 67";
$_CONFIG['contactPlace']              = "Musterhausen";
$_CONFIG['contactZip']                = 3600;
$_CONFIG['coreAdminEmail']            = "info@example.com";
$_CONFIG['coreAdminName']             = "Administrator";
$_CONFIG['coreGlobalPageTitle']       = "Default Installation";
$_CONFIG['coreIdsStatus']             = "off";
$_CONFIG['coreListProtectedPages']    = "off";
$_CONFIG['corePagingLimit']           = 30;
$_CONFIG['coreSmtpServer']            = 0;
$_CONFIG['dashboardNews']             = "on";
$_CONFIG['dashboardStatistics']       = "on";
$_CONFIG['dnsServer']                 = "ns1.contrexxhosting.com";
$_CONFIG['domainUrl']                 = "contrexx3.dev";
$_CONFIG['frontendEditingStatus']     = "off";
$_CONFIG['googleAnalyticsTrackingId'] = "";
$_CONFIG['googleMapsAPIKey']          = "";
$_CONFIG['installationId']            = "";
$_CONFIG['languageDetection']         = "on";
$_CONFIG['lastAccessId']              = 382;
$_CONFIG['licenseKey']                = "";
$_CONFIG['passwordComplexity']        = "on";
$_CONFIG['protocolHttpsBackend']      = "off";
$_CONFIG['protocolHttpsFrontend']     = "off";
$_CONFIG['searchVisibleContentOnly']  = "on";
$_CONFIG['sessionLifeTime']           = 3600;
$_CONFIG['sessionLifeTimeRememberMe'] = 1209600;
$_CONFIG['spamKeywords']              = "sex, viagra";
$_CONFIG['systemStatus']              = "on";
$_CONFIG['timezone']                  = "Europe/Zurich";
$_CONFIG['useCustomizings']           = "on";
$_CONFIG['xmlSitemapStatus']          = "on";
>>>>>>> f7ee35166c3ea0314d3113cfac8fc8894c4d0211

/**
* -------------------------------------------------------------------------
* Search
* -------------------------------------------------------------------------
*/
<<<<<<< HEAD
$_CONFIG['searchDescriptionLength']      = 150;
=======
$_CONFIG['searchDescriptionLength']   = 150;
>>>>>>> f7ee35166c3ea0314d3113cfac8fc8894c4d0211

/**
* -------------------------------------------------------------------------
* Contact
* -------------------------------------------------------------------------
*/
<<<<<<< HEAD
$_CONFIG['contactFormEmail']             = "info@example.com";
=======
$_CONFIG['contactFormEmail']          = "info@example.com";
>>>>>>> f7ee35166c3ea0314d3113cfac8fc8894c4d0211

/**
* -------------------------------------------------------------------------
* Block
* -------------------------------------------------------------------------
*/
<<<<<<< HEAD
$_CONFIG['blockRandom']                  = 1;
$_CONFIG['blockStatus']                  = 1;
=======
$_CONFIG['blockRandom']               = 1;
$_CONFIG['blockStatus']               = 1;
>>>>>>> f7ee35166c3ea0314d3113cfac8fc8894c4d0211

/**
* -------------------------------------------------------------------------
* News
* -------------------------------------------------------------------------
*/
<<<<<<< HEAD
$_CONFIG['newsTeasersStatus']            = 0;
=======
$_CONFIG['newsTeasersStatus']         = 1;
>>>>>>> f7ee35166c3ea0314d3113cfac8fc8894c4d0211

/**
* -------------------------------------------------------------------------
* Directory
* -------------------------------------------------------------------------
*/
<<<<<<< HEAD
$_CONFIG['directoryHomeContent']         = 0;
=======
$_CONFIG['directoryHomeContent']      = 0;
>>>>>>> f7ee35166c3ea0314d3113cfac8fc8894c4d0211

/**
* -------------------------------------------------------------------------
* Forum
* -------------------------------------------------------------------------
*/
<<<<<<< HEAD
$_CONFIG['forumHomeContent']             = 1;
$_CONFIG['forumTagContent']              = 0;
=======
$_CONFIG['forumHomeContent']          = 1;
$_CONFIG['forumTagContent']           = 0;
>>>>>>> f7ee35166c3ea0314d3113cfac8fc8894c4d0211

/**
* -------------------------------------------------------------------------
* Calendar
* -------------------------------------------------------------------------
*/
<<<<<<< HEAD
$_CONFIG['calendardefaultcount']         = 16;
$_CONFIG['calendarheadlines']            = 1;
$_CONFIG['calendarheadlinescat']         = 0;
$_CONFIG['calendarheadlinescount']       = 1;
=======
$_CONFIG['calendardefaultcount']      = 16;
$_CONFIG['calendarheadlines']         = 1;
$_CONFIG['calendarheadlinescat']      = 0;
$_CONFIG['calendarheadlinescount']    = 5;
>>>>>>> f7ee35166c3ea0314d3113cfac8fc8894c4d0211

/**
* -------------------------------------------------------------------------
* Feed
* -------------------------------------------------------------------------
*/
<<<<<<< HEAD
$_CONFIG['feedNewsMLStatus']             = 0;
=======
$_CONFIG['feedNewsMLStatus']          = 0;
>>>>>>> f7ee35166c3ea0314d3113cfac8fc8894c4d0211

/**
* -------------------------------------------------------------------------
* 
* -------------------------------------------------------------------------
*/
<<<<<<< HEAD
$_CONFIG['bannerStatus']                 = 0;
=======
$_CONFIG['bannerStatus']              = 0;
>>>>>>> f7ee35166c3ea0314d3113cfac8fc8894c4d0211

/**
* -------------------------------------------------------------------------
* Podcast
* -------------------------------------------------------------------------
*/
<<<<<<< HEAD
$_CONFIG['podcastHomeContent']           = 1;
=======
$_CONFIG['podcastHomeContent']        = 1;
>>>>>>> f7ee35166c3ea0314d3113cfac8fc8894c4d0211

/**
* -------------------------------------------------------------------------
* Data
* -------------------------------------------------------------------------
*/
<<<<<<< HEAD
$_CONFIG['dataUseModule']                = 1;
=======
$_CONFIG['dataUseModule']             = 1;
>>>>>>> f7ee35166c3ea0314d3113cfac8fc8894c4d0211

/**
* -------------------------------------------------------------------------
* Upload
* -------------------------------------------------------------------------
*/
<<<<<<< HEAD
$_CONFIG['advancedUploadBackend']        = "on";
$_CONFIG['advancedUploadFrontend']       = "off";
=======
$_CONFIG['advancedUploadBackend']     = "on";
$_CONFIG['advancedUploadFrontend']    = "off";
>>>>>>> f7ee35166c3ea0314d3113cfac8fc8894c4d0211

/**
* -------------------------------------------------------------------------
* Knowledge
* -------------------------------------------------------------------------
*/
<<<<<<< HEAD
$_CONFIG['useKnowledgePlaceholders']     = 1;
=======
$_CONFIG['useKnowledgePlaceholders']  = 1;
>>>>>>> f7ee35166c3ea0314d3113cfac8fc8894c4d0211

/**
* -------------------------------------------------------------------------
* License
* -------------------------------------------------------------------------
*/
<<<<<<< HEAD
$_CONFIG['availableComponents']          = "Tzo4OiJzdGRDbGFzcyI6MTp7czoxMjoiQ29tdmF0aW9uIEFHIjthOjY1OntpOjA7czo2OiJhY2Nlc3MiO2k6MTtzOjM6ImFnYiI7aToyO3M6NToiYWxpYXMiO2k6MztzOjU6ImJsb2NrIjtpOjQ7czo3OiJjYXB0Y2hhIjtpOjU7czo3OiJjb250YWN0IjtpOjY7czo0OiJjb3JlIjtpOjc7czo5OiJkb3dubG9hZHMiO2k6ODtzOjU6ImVycm9yIjtpOjk7czoxMToiZmlsZUJyb3dzZXIiO2k6MTA7czoxMToiZmlsZXNoYXJpbmciO2k6MTE7czo0OiJob21lIjtpOjEyO3M6MzoiaWRzIjtpOjEzO3M6NDoiaW1tbyI7aToxNDtzOjc6ImltcHJpbnQiO2k6MTU7czo4OiJqc29uZGF0YSI7aToxNjtzOjg6Imxhbmd1YWdlIjtpOjE3O3M6NzoibGljZW5zZSI7aToxODtzOjU6ImxvZ2luIjtpOjE5O3M6NjoibG9nb3V0IjtpOjIwO3M6NjoibWVkaWExIjtpOjIxO3M6NjoibWVkaWEyIjtpOjIyO3M6NjoibWVkaWEzIjtpOjIzO3M6NjoibWVkaWE0IjtpOjI0O3M6ODoibmV0dG9vbHMiO2k6MjU7czo0OiJuZXdzIjtpOjI2O3M6NzoicHJpdmFjeSI7aToyNztzOjY6InNlYXJjaCI7aToyODtzOjc6InNpdGVtYXAiO2k6Mjk7czo1OiJzdGF0cyI7aTozMDtzOjY6InVwbG9hZCI7aTozMTtzOjQ6ImJsb2ciO2k6MzI7czo1OiJlY2FyZCI7aTozMztzOjc6ImdhbGxlcnkiO2k6MzQ7czo5OiJndWVzdGJvb2siO2k6MzU7czo5OiJyZWNvbW1lbmQiO2k6MzY7czozOiJ1MnUiO2k6Mzc7czoxMjoiZnVsbGxhbmd1YWdlIjtpOjM4O3M6NDoic2hvcCI7aTozOTtzOjg6ImNoZWNrb3V0IjtpOjQwO3M6MTA6Im5ld3NsZXR0ZXIiO2k6NDE7czo3OiJhdWN0aW9uIjtpOjQyO3M6NDoiYmxvZyI7aTo0MztzOjg6ImNhbGVuZGFyIjtpOjQ0O3M6NDoiZGF0YSI7aTo0NTtzOjk6ImRpcmVjdG9yeSI7aTo0NjtzOjY6ImRvY3N5cyI7aTo0NztzOjU6ImVjYXJkIjtpOjQ4O3M6NDoiZWdvdiI7aTo0OTtzOjQ6ImZlZWQiO2k6NTA7czo1OiJmb3J1bSI7aTo1MTtzOjc6ImdhbGxlcnkiO2k6NTI7czo5OiJndWVzdGJvb2siO2k6NTM7czo1OiJob3RlbCI7aTo1NDtzOjQ6ImpvYnMiO2k6NTU7czo5OiJrbm93bGVkZ2UiO2k6NTY7czo3OiJsaXZlY2FtIjtpOjU3O3M6NjoibWFya2V0IjtpOjU4O3M6ODoibWVkaWFkaXIiO2k6NTk7czo5OiJtZW1iZXJkaXIiO2k6NjA7czo4OiJwYXJ0bmVycyI7aTo2MTtzOjc6InBvZGNhc3QiO2k6NjI7czo5OiJyZWNvbW1lbmQiO2k6NjM7czozOiJ1MnUiO2k6NjQ7czo2OiJ2b3RpbmciO319";
$_CONFIG['coreCmsCodeName']              = "Nikola Tesla";
$_CONFIG['coreCmsEdition']               = "";
$_CONFIG['coreCmsName']                  = "Contrexx";
$_CONFIG['coreCmsReleaseDate']           = 1348783200;
$_CONFIG['coreCmsStatus']                = "stable";
$_CONFIG['coreCmsVersion']               = "4.0.0";
$_CONFIG['dashboardMessages']            = "YToxOntzOjI6ImRlIjtPOjMxOiJDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlIjo2OntzOjQxOiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcTWVzc2FnZQBsYW5nQ29kZSI7czoyOiJkZSI7czozNzoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXE1lc3NhZ2UAdGV4dCI7czowOiIiO3M6Mzc6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlAHR5cGUiO3M6MTA6Indhcm5pbmdib3giO3M6Mzc6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlAGxpbmsiO3M6MjE6ImluZGV4LnBocD9jbWQ9bGljZW5zZSI7czo0MzoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXE1lc3NhZ2UAbGlua1RhcmdldCI7czo1OiJfc2VsZiI7czo0ODoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXE1lc3NhZ2UAc2hvd0luRGFzaGJvYXJkIjtiOjE7fX0=";
$_CONFIG['isUpgradable']                 = "off";
$_CONFIG['licenseCreatedAt']             = 1414486530;
$_CONFIG['licenseCustomer']              = "TzozMDoiQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uIjoxMTp7czo0MzoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXFBlcnNvbgBjb21wYW55TmFtZSI7czoxMjoiQ29tdmF0aW9uIEFHIjtzOjM3OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uAHRpdGxlIjtzOjM6Ik1yLiI7czo0MToiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXFBlcnNvbgBmaXJzdG5hbWUiO3M6NDoiSGFucyI7czo0MDoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXFBlcnNvbgBsYXN0bmFtZSI7czo2OiJNdXN0ZXIiO3M6Mzk6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxQZXJzb24AYWRkcmVzcyI7czoxNDoiQnVyZ3N0cmFzc2UgMjAiO3M6MzU6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxQZXJzb24AemlwIjtzOjQ6IjM2MDAiO3M6MzY6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxQZXJzb24AY2l0eSI7czo0OiJUaHVuIjtzOjM5OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uAGNvdW50cnkiO3M6MTE6IlN3aXR6ZXJsYW5kIjtzOjM3OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uAHBob25lIjtzOjE4OiIrNDEgKDApMzMgMjI2IDYwMDAiO3M6MzU6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxQZXJzb24AdXJsIjtzOjI1OiJodHRwOi8vd3d3LmNvbXZhdGlvbi5jb20vIjtzOjM2OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uAG1haWwiO3M6MTg6ImluZm9AY29tdmF0aW9uLmNvbSI7fQ==";
$_CONFIG['licenseDomains']               = "YToxOntpOjA7czoxNjoiaW5mb0BleGFtcGxlLmNvbSI7fQ==";
$_CONFIG['licenseFailedUpdate']          = 0;
$_CONFIG['licenseGrayzoneMessages']      = "YToxOntzOjI6ImRlIjtPOjMxOiJDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlIjo2OntzOjQxOiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcTWVzc2FnZQBsYW5nQ29kZSI7czoyOiJkZSI7czozNzoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXE1lc3NhZ2UAdGV4dCI7czo3MjoiRXMgaXN0IGVpbiBGZWhsZXIgYXVmZ2V0cmV0ZW4uIEJpdHRlIHdlbmRlbiBTaWUgc2ljaCBhbiBJaHJlbiBXZWJtYXN0ZXIuIjtzOjM3OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcTWVzc2FnZQB0eXBlIjtzOjg6ImFsZXJ0Ym94IjtzOjM3OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcTWVzc2FnZQBsaW5rIjtzOjIxOiJpbmRleC5waHA/Y21kPWxpY2Vuc2UiO3M6NDM6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlAGxpbmtUYXJnZXQiO3M6NToiX3NlbGYiO3M6NDg6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlAHNob3dJbkRhc2hib2FyZCI7YjoxO319";
$_CONFIG['licenseGrayzoneTime']          = 14;
$_CONFIG['licenseLockTime']              = "false";
$_CONFIG['licenseMessage']               = "YToxOntzOjI6ImRlIjtPOjMxOiJDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlIjo2OntzOjQxOiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcTWVzc2FnZQBsYW5nQ29kZSI7czoyOiJkZSI7czozNzoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXE1lc3NhZ2UAdGV4dCI7czowOiIiO3M6Mzc6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlAHR5cGUiO3M6MTA6Indhcm5pbmdib3giO3M6Mzc6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlAGxpbmsiO3M6Mjg6Imh0dHA6Ly9saWNlbnNlLmNvbnRyZXh4LmNvbS8iO3M6NDM6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlAGxpbmtUYXJnZXQiO3M6NjoiX2JsYW5rIjtzOjQ4OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcTWVzc2FnZQBzaG93SW5EYXNoYm9hcmQiO2I6MTt9fQ==";
$_CONFIG['licensePartner']               = "TzozMDoiQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uIjoxMTp7czo0MzoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXFBlcnNvbgBjb21wYW55TmFtZSI7czoxMjoiQ29tdmF0aW9uIEFHIjtzOjM3OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uAHRpdGxlIjtzOjM6Ik1yLiI7czo0MToiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXFBlcnNvbgBmaXJzdG5hbWUiO3M6NDoiSGFucyI7czo0MDoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXFBlcnNvbgBsYXN0bmFtZSI7czo2OiJNdXN0ZXIiO3M6Mzk6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxQZXJzb24AYWRkcmVzcyI7czoxNDoiQnVyZ3N0cmFzc2UgMjAiO3M6MzU6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxQZXJzb24AemlwIjtzOjQ6IjM2MDAiO3M6MzY6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxQZXJzb24AY2l0eSI7czo0OiJUaHVuIjtzOjM5OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uAGNvdW50cnkiO3M6MTE6IlN3aXR6ZXJsYW5kIjtzOjM3OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uAHBob25lIjtzOjE4OiIrNDEgKDApMzMgMjI2IDYwMDAiO3M6MzU6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxQZXJzb24AdXJsIjtzOjI1OiJodHRwOi8vd3d3LmNvbXZhdGlvbi5jb20vIjtzOjM2OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uAG1haWwiO3M6MTg6ImluZm9AY29tdmF0aW9uLmNvbSI7fQ==";
$_CONFIG['licenseState']                 = "OK";
$_CONFIG['licenseSuccessfulUpdate']      = 1414594354;
$_CONFIG['licenseUpdateInterval']        = 24;
$_CONFIG['licenseValidTo']               = 1761641730;
$_CONFIG['upgradeUrl']                   = "http://license.contrexx.com/";

?>
=======
$_CONFIG['availableComponents']       = "Tzo4OiJzdGRDbGFzcyI6MTp7czoxMjoiQ29tdmF0aW9uIEFHIjthOjY1OntpOjA7czo2OiJhY2Nlc3MiO2k6MTtzOjM6ImFnYiI7aToyO3M6NToiYWxpYXMiO2k6MztzOjU6ImJsb2NrIjtpOjQ7czo3OiJjYXB0Y2hhIjtpOjU7czo3OiJjb250YWN0IjtpOjY7czo0OiJjb3JlIjtpOjc7czo5OiJkb3dubG9hZHMiO2k6ODtzOjU6ImVycm9yIjtpOjk7czoxMToiZmlsZUJyb3dzZXIiO2k6MTA7czoxMToiZmlsZXNoYXJpbmciO2k6MTE7czo0OiJob21lIjtpOjEyO3M6MzoiaWRzIjtpOjEzO3M6NDoiaW1tbyI7aToxNDtzOjc6ImltcHJpbnQiO2k6MTU7czo4OiJqc29uZGF0YSI7aToxNjtzOjg6Imxhbmd1YWdlIjtpOjE3O3M6NzoibGljZW5zZSI7aToxODtzOjU6ImxvZ2luIjtpOjE5O3M6NjoibG9nb3V0IjtpOjIwO3M6NjoibWVkaWExIjtpOjIxO3M6NjoibWVkaWEyIjtpOjIyO3M6NjoibWVkaWEzIjtpOjIzO3M6NjoibWVkaWE0IjtpOjI0O3M6ODoibmV0dG9vbHMiO2k6MjU7czo0OiJuZXdzIjtpOjI2O3M6NzoicHJpdmFjeSI7aToyNztzOjY6InNlYXJjaCI7aToyODtzOjc6InNpdGVtYXAiO2k6Mjk7czo1OiJzdGF0cyI7aTozMDtzOjY6InVwbG9hZCI7aTozMTtzOjQ6ImJsb2ciO2k6MzI7czo1OiJlY2FyZCI7aTozMztzOjc6ImdhbGxlcnkiO2k6MzQ7czo5OiJndWVzdGJvb2siO2k6MzU7czo5OiJyZWNvbW1lbmQiO2k6MzY7czozOiJ1MnUiO2k6Mzc7czoxMjoiZnVsbGxhbmd1YWdlIjtpOjM4O3M6NDoic2hvcCI7aTozOTtzOjg6ImNoZWNrb3V0IjtpOjQwO3M6MTA6Im5ld3NsZXR0ZXIiO2k6NDE7czo3OiJhdWN0aW9uIjtpOjQyO3M6NDoiYmxvZyI7aTo0MztzOjg6ImNhbGVuZGFyIjtpOjQ0O3M6NDoiZGF0YSI7aTo0NTtzOjk6ImRpcmVjdG9yeSI7aTo0NjtzOjY6ImRvY3N5cyI7aTo0NztzOjU6ImVjYXJkIjtpOjQ4O3M6NDoiZWdvdiI7aTo0OTtzOjQ6ImZlZWQiO2k6NTA7czo1OiJmb3J1bSI7aTo1MTtzOjc6ImdhbGxlcnkiO2k6NTI7czo5OiJndWVzdGJvb2siO2k6NTM7czo1OiJob3RlbCI7aTo1NDtzOjQ6ImpvYnMiO2k6NTU7czo5OiJrbm93bGVkZ2UiO2k6NTY7czo3OiJsaXZlY2FtIjtpOjU3O3M6NjoibWFya2V0IjtpOjU4O3M6ODoibWVkaWFkaXIiO2k6NTk7czo5OiJtZW1iZXJkaXIiO2k6NjA7czo4OiJwYXJ0bmVycyI7aTo2MTtzOjc6InBvZGNhc3QiO2k6NjI7czo5OiJyZWNvbW1lbmQiO2k6NjM7czozOiJ1MnUiO2k6NjQ7czo2OiJ2b3RpbmciO319";
$_CONFIG['coreCmsCodeName']           = "Nikola Tesla";
$_CONFIG['coreCmsEdition']            = "Trial";
$_CONFIG['coreCmsName']               = "Contrexx";
$_CONFIG['coreCmsReleaseDate']        = 1348783200;
$_CONFIG['coreCmsStatus']             = "stable";
$_CONFIG['coreCmsVersion']            = "3.1.0";
$_CONFIG['dashboardMessages']         = "YToxOntzOjI6ImRlIjtPOjMxOiJDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlIjo2OntzOjQxOiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcTWVzc2FnZQBsYW5nQ29kZSI7czoyOiJkZSI7czozNzoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXE1lc3NhZ2UAdGV4dCI7czo0NzoiRXMgc3RlaGVuIFdhcnR1bmdzYXJiZWl0ZW4gYW4uIMK7IE1laHIgZXJmYWhyZW4iO3M6Mzc6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlAHR5cGUiO3M6MTA6Indhcm5pbmdib3giO3M6Mzc6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlAGxpbmsiO3M6MjE6ImluZGV4LnBocD9jbWQ9bGljZW5zZSI7czo0MzoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXE1lc3NhZ2UAbGlua1RhcmdldCI7czo1OiJfc2VsZiI7czo0ODoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXE1lc3NhZ2UAc2hvd0luRGFzaGJvYXJkIjtiOjE7fX0=";
$_CONFIG['isUpgradable']              = "on";
$_CONFIG['licenseCreatedAt']          = 1369899440;
$_CONFIG['licenseCustomer']           = "TzozMDoiQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uIjoxMTp7czo0MzoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXFBlcnNvbgBjb21wYW55TmFtZSI7czoxMjoiQ29tdmF0aW9uIEFHIjtzOjM3OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uAHRpdGxlIjtzOjM6Ik1yLiI7czo0MToiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXFBlcnNvbgBmaXJzdG5hbWUiO3M6NDoiSGFucyI7czo0MDoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXFBlcnNvbgBsYXN0bmFtZSI7czo2OiJNdXN0ZXIiO3M6Mzk6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxQZXJzb24AYWRkcmVzcyI7czoxNDoiQnVyZ3N0cmFzc2UgMjAiO3M6MzU6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxQZXJzb24AemlwIjtzOjQ6IjM2MDAiO3M6MzY6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxQZXJzb24AY2l0eSI7czo0OiJUaHVuIjtzOjM5OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uAGNvdW50cnkiO3M6MTE6IlN3aXR6ZXJsYW5kIjtzOjM3OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uAHBob25lIjtzOjE4OiIrNDEgKDApMzMgMjI2IDYwMDAiO3M6MzU6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxQZXJzb24AdXJsIjtzOjI1OiJodHRwOi8vd3d3LmNvbXZhdGlvbi5jb20vIjtzOjM2OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uAG1haWwiO3M6MTg6ImluZm9AY29tdmF0aW9uLmNvbSI7fQ==";
$_CONFIG['licenseDomains']            = "YToxOntpOjA7czoyNDoic3RhZ2luZy5jb250cmV4eGxhYnMuY29tIjt9";
$_CONFIG['licenseFailedUpdate']       = 0;
$_CONFIG['licenseGrayzoneMessages']   = "YToxOntzOjI6ImRlIjtPOjMxOiJDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlIjo2OntzOjQxOiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcTWVzc2FnZQBsYW5nQ29kZSI7czoyOiJkZSI7czozNzoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXE1lc3NhZ2UAdGV4dCI7czoxMDQ6IkJlaW0gQWt0dWFsaXNpZXJlbiBkZXIgTGl6ZW56ZGF0ZW4gaXN0IGVpbiBGZWhsZXIgYXVmZ2V0cmV0ZW4uIEJpdHRlIHdlbmRlbiBTaWUgc2ljaCBhbiBJaHJlbiBXZWJtYXN0ZXIuIjtzOjM3OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcTWVzc2FnZQB0eXBlIjtzOjg6ImFsZXJ0Ym94IjtzOjM3OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcTWVzc2FnZQBsaW5rIjtzOjIxOiJpbmRleC5waHA/Y21kPWxpY2Vuc2UiO3M6NDM6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlAGxpbmtUYXJnZXQiO3M6NToiX3NlbGYiO3M6NDg6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlAHNob3dJbkRhc2hib2FyZCI7YjoxO319";
$_CONFIG['licenseGrayzoneTime']       = 14;
$_CONFIG['licenseLockTime']           = "false";
$_CONFIG['licenseMessage']            = "YToxOntzOjI6ImRlIjtPOjMxOiJDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlIjo2OntzOjQxOiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcTWVzc2FnZQBsYW5nQ29kZSI7czoyOiJkZSI7czozNzoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXE1lc3NhZ2UAdGV4dCI7czoxOTg6IlNpZSB2ZXJ3ZW5kZW4gZGllIFRyaWFsIExpemVuei4gRXJ3ZXJiZW4gU2llIGpldHp0IElocmUgQ29udHJleHggQnVzaW5lc3MgTGl6ZW56LCB1bSB3ZWl0ZXJoaW4gZGVuIHZvbGxlbiBGdW5rdGlvbnN1bWZhbmcgdm9uIENvbnRyZXh4IG51dHplbiB6dSBrw7ZubmVuICh7TElDRU5TRV9WQUxJRF9EQVlfQ09VTlR9IFRhZ2UgdmVyYmxlaWJlbmQpLiI7czozNzoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXE1lc3NhZ2UAdHlwZSI7czoxMDoid2FybmluZ2JveCI7czozNzoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXE1lc3NhZ2UAbGluayI7czoyODoiaHR0cDovL2xpY2Vuc2UuY29udHJleHguY29tLyI7czo0MzoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXE1lc3NhZ2UAbGlua1RhcmdldCI7czo2OiJfYmxhbmsiO3M6NDg6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxNZXNzYWdlAHNob3dJbkRhc2hib2FyZCI7YjoxO319";
$_CONFIG['licensePartner']            = "TzozMDoiQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uIjoxMTp7czo0MzoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXFBlcnNvbgBjb21wYW55TmFtZSI7czoxMjoiQ29tdmF0aW9uIEFHIjtzOjM3OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uAHRpdGxlIjtzOjM6Ik1yLiI7czo0MToiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXFBlcnNvbgBmaXJzdG5hbWUiO3M6NDoiSGFucyI7czo0MDoiAEN4XENvcmVfTW9kdWxlc1xMaWNlbnNlXFBlcnNvbgBsYXN0bmFtZSI7czo2OiJNdXN0ZXIiO3M6Mzk6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxQZXJzb24AYWRkcmVzcyI7czoxNDoiQnVyZ3N0cmFzc2UgMjAiO3M6MzU6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxQZXJzb24AemlwIjtzOjQ6IjM2MDAiO3M6MzY6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxQZXJzb24AY2l0eSI7czo0OiJUaHVuIjtzOjM5OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uAGNvdW50cnkiO3M6MTE6IlN3aXR6ZXJsYW5kIjtzOjM3OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uAHBob25lIjtzOjE4OiIrNDEgKDApMzMgMjI2IDYwMDAiO3M6MzU6IgBDeFxDb3JlX01vZHVsZXNcTGljZW5zZVxQZXJzb24AdXJsIjtzOjI1OiJodHRwOi8vd3d3LmNvbXZhdGlvbi5jb20vIjtzOjM2OiIAQ3hcQ29yZV9Nb2R1bGVzXExpY2Vuc2VcUGVyc29uAG1haWwiO3M6MTg6ImluZm9AY29tdmF0aW9uLmNvbSI7fQ==";
$_CONFIG['licenseState']              = "NOK";
$_CONFIG['licenseSuccessfulUpdate']   = 0;
$_CONFIG['licenseUpdateInterval']     = 24;
$_CONFIG['licenseValidTo']            = 0;
$_CONFIG['upgradeUrl']                = "http://license.contrexx.com/";

?>
>>>>>>> f7ee35166c3ea0314d3113cfac8fc8894c4d0211
