<?php
/**
* This file is generated by the "settings"-menu in your CMS.
* Do not try to edit it manually!
*/

/**
* -------------------------------------------------------------------------
* Core
* -------------------------------------------------------------------------
*/
$_CONFIG['cacheEnabled']             = "off";
$_CONFIG['cacheExpiration']          = 86400;
$_CONFIG['contentHistoryStatus']     = "on";
$_CONFIG['coreAdminEmail']           = "reto.kohli@comvation.com";
$_CONFIG['coreAdminName']            = "Reto Kohli";
$_CONFIG['coreGlobalPageTitle']      = "Contrexx Development";
$_CONFIG['coreIdsStatus']            = "on";
$_CONFIG['corePagingLimit']          = 30;
$_CONFIG['dnsServer']                = "contrexxhosting.com";
$_CONFIG['domainUrl']                = "localhost";
$_CONFIG['googleSitemapStatus']      = "off";
$_CONFIG['langDebugIds']             = "off";
$_CONFIG['lastAccessId']             = 50;
$_CONFIG['searchVisibleContentOnly'] = "off";
$_CONFIG['sessionLifeTime']          = 3600;
$_CONFIG['spamKeywords']             = "sex, viagra";
$_CONFIG['systemStatus']             = "on";

/**
* -------------------------------------------------------------------------
* Search
* -------------------------------------------------------------------------
*/
$_CONFIG['searchDescriptionLength']  = 150;

/**
* -------------------------------------------------------------------------
* Contact
* -------------------------------------------------------------------------
*/
$_CONFIG['contactFormEmail']         = "reto.kohli@comvation.com";

/**
* -------------------------------------------------------------------------
* Block
* -------------------------------------------------------------------------
*/
$_CONFIG['blockRandom']              = 1;
$_CONFIG['blockStatus']              = 1;

/**
* -------------------------------------------------------------------------
* News
* -------------------------------------------------------------------------
*/
$_CONFIG['newsTeasersStatus']        = 1;

/**
* -------------------------------------------------------------------------
* Directory
* -------------------------------------------------------------------------
*/
$_CONFIG['directoryHomeContent']     = 1;

/**
* -------------------------------------------------------------------------
* Forum
* -------------------------------------------------------------------------
*/
$_CONFIG['forumHomeContent']         = 1;

/**
* -------------------------------------------------------------------------
* Calendar
* -------------------------------------------------------------------------
*/
$_CONFIG['calendardefaultcount']     = 16;
$_CONFIG['calendarheadlines']        = 1;
$_CONFIG['calendarheadlinescat']     = "0";
$_CONFIG['calendarheadlinescount']   = 5;

/**
* -------------------------------------------------------------------------
* Feed
* -------------------------------------------------------------------------
*/
$_CONFIG['feedNewsMLStatus']         = 1;

/**
* -------------------------------------------------------------------------
* Banner
* -------------------------------------------------------------------------
*/
$_CONFIG['bannerStatus']             = 1;

/**
* -------------------------------------------------------------------------
* Alias
* -------------------------------------------------------------------------
*/
$_CONFIG['aliasStatus']              = 1;

/**
* -------------------------------------------------------------------------
* FileUploader
* -------------------------------------------------------------------------
*/
$_CONFIG['fileUploaderStatus']       = "off";

?>
