<?php

namespace Cx\Model\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CxModelContentManagerSkinProxy extends \Cx\Model\ContentManager\Skin implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setThemesname($themesname)
    {
        $this->_load();
        return parent::setThemesname($themesname);
    }

    public function getThemesname()
    {
        $this->_load();
        return parent::getThemesname();
    }

    public function setFoldername($foldername)
    {
        $this->_load();
        return parent::setFoldername($foldername);
    }

    public function getFoldername()
    {
        $this->_load();
        return parent::getFoldername();
    }

    public function setExpert($expert)
    {
        $this->_load();
        return parent::setExpert($expert);
    }

    public function getExpert()
    {
        $this->_load();
        return parent::getExpert();
    }

    public function addPages(\Cx\Model\ContentManager\Page $pages)
    {
        $this->_load();
        return parent::addPages($pages);
    }

    public function getPages()
    {
        $this->_load();
        return parent::getPages();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'themesname', 'foldername', 'expert', 'pages');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}