<?php

namespace Cx\Core\Locale\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BackendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackendRepository extends EntityRepository
{
}