<?php

namespace Cx\Core\Locale\Model\LocaleRepository;

use Doctrine\ORM\EntityRepository;

/**
 * LocaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocaleRepository extends EntityRepository
{
}